// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/LayerList/PopupMenu.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"popup-menu-transparency-body" data-dojo-attach-point\x3d"transparencyDiv" data-dojo-attach-event\x3d"onclick:_onTransparencyDivClick" \x3e\r\n    \x3cdiv class\x3d"label"\x3e\r\n      \x3cdiv class\x3d"label-left jimu-float-leading"\x3e${nls.itemOpaque}\x3c/div\x3e\r\n      \x3cdiv class\x3d"label-right jimu-float-trailing"\x3e${nls.itemTransparent}\x3c/div\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"transparencyBody"\x3e \r\n      \x3col data-dojo-attach-point\x3d"transparencyRule" class\x3d"transparency-rule"\x3e \x3c/ol\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"popup-menu-visible-scale-range-body" data-dojo-attach-point\x3d"setVisibilityRangeNode" data-dojo-attach-event\x3d"onclick:_onSetVisibilityRangeNode"\x3e \r\n  \x3c/div\x3e\r\n\x3cdiv\x3e\r\n'}});
define("dojo/_base/declare dojo/_base/array dojo/_base/html dojo/_base/lang dojo/query dojo/on dojo/keys dijit/focus dojo/Deferred jimu/dijit/DropMenu jimu/utils dijit/_TemplatedMixin dijit/form/HorizontalSlider dijit/form/HorizontalRuleLabels dojo/text!./PopupMenu.html dojo/dom-style esri/dijit/VisibleScaleRangeSlider ./NlsStrings ./PopupMenuInfo".split(" "),function(q,p,b,d,h,m,f,k,r,t,u,v,w,x,y,g,z,A,B){return q([t,v],{templateString:y,popupMenuInfo:null,loading:null,_deniedItems:null,_deniedItemsFromConfig:null,
_layerInfo:null,constructor:function(){this.nls=A.value},postCreate:function(){this.inherited(arguments);this._initDeniedItems();this.loading=b.create("div",{"class":"popup-menu-loading"},this.popupMenuNode)},_initDeniedItems:function(){var a=[],c={ZoomTo:"zoomto",Transparency:"transparency",SetVisibilityRange:"setVisibilityRange",EnableOrDisablePopup:"controlPopup",ControlLabels:"controlLabels",MoveupOrMovedown:"moveup movedown",OpenAttributeTable:"table",DescriptionOrShowItemDetailsOrDownload:"url"};
this._deniedItems=[];this._deniedItemsFromConfig=[];for(var e in this._config.contextMenu)this._config.contextMenu.hasOwnProperty(e)&&"function"!==typeof this._config.contextMenu[e]&&!1===this._config.contextMenu[e]&&(a=a.concat(c[e].split(" ")));p.forEach(a,d.hitch(this,function(a){this._deniedItemsFromConfig.push({key:a,denyType:"hidden"})}))},_getDropMenuPosition:function(){return{top:"40px",right:"0px",zIndex:1}},_getTransNodePosition:function(){return{top:"28px",right:"2px"}},_onBtnClick:function(){},
_refresh:function(){this._denyItems();this._changeItemsUI()},_denyItems:function(){var a=h("[class~\x3d'menu-item-identification']",this.dropMenuNode);a.forEach(function(a){b.removeClass(a,"menu-item-dissable");b.removeClass(a,"menu-item-hidden")},this);b.removeClass(this.dropMenuNode,"no-border");p.forEach(this._deniedItems,function(a){var c=h("div[itemId\x3d'"+a.key+"']",this.dropMenuNode)[0];c&&("disable"===a.denyType?(b.addClass(c,"menu-item-dissable"),b.setAttr(c,"aria-disabled","true"),"url"===
a.key&&h(".menu-item-description",c).forEach(function(a){b.setAttr(a,"href","#");b.removeAttr(a,"target")})):(b.removeAttr(c,"aria-disabled"),b.addClass(c,"menu-item-hidden")))},this);for(var c=-1,e=0;e<a.length;e++)b.hasClass(a[e],"menu-item-line")&&(-1===c||b.hasClass(a[c],"menu-item-line"))&&b.addClass(a[e],"menu-item-hidden"),b.hasClass(a[e],"menu-item-hidden")||(c=e);a=p.filter(a,function(a){return!b.hasClass(a,"menu-item-hidden")});0===a.length?b.addClass(this.dropMenuNode,"no-border"):(b.removeClass(this.dropMenuNode,
"no-border"),b.hasClass(a[a.length-1],"menu-item-line")&&b.addClass(a[a.length-1],"menu-item-hidden"))},_changeItemsUI:function(){var a=h("[itemid\x3dcontrolPopup]",this.dropMenuNode)[0];a&&(this._layerInfo.isPopupNestedEnabled()?b.setAttr(a,"innerHTML",this.nls.removePopup):b.setAttr(a,"innerHTML",this.nls.enablePopup));(a=h("[itemid\x3dcontrolLabels]",this.dropMenuNode)[0])&&this._layerInfo.canShowLabel()&&(this._layerInfo.isShowLabels()?b.setAttr(a,"innerHTML",this.nls.hideLables):b.setAttr(a,
"innerHTML",this.nls.showLabels));(a=h("[itemid\x3durl] a",this.dropMenuNode)[0])&&b.setAttr(a,"target","_blank")},_switchLoadingState:function(a){a?b.setStyle(this.loading,"display","block"):b.setStyle(this.loading,"display","none")},selectItem:function(a,c){for(var e=!1,b=0;b<this._deniedItems.length;b++)if(this._deniedItems[b].key===a.key){e=!0;break}e||this.emit("onMenuClick",a);c.stopPropagation(c)},openDropMenu:function(){var a=d.hitch(this,this.inherited,arguments),c=new r;this._switchLoadingState(!0);
this.dropMenuNode?c.resolve(this.popupMenuInfo):B.create(this._layerInfo,this.layerListWidget).then(d.hitch(this,function(a){this.items=a.getDisplayItems();this.popupMenuInfo=a;this._createDropMenuNode();c.resolve(this.popupMenuInfo)}));c.then(d.hitch(this,function(){this.popupMenuInfo.getDeniedItems().then(d.hitch(this,function(c){this._deniedItems=this._deniedItemsFromConfig.concat(c);this._refresh();a(arguments);this._switchLoadingState(!1)}),d.hitch(this,function(){this._switchLoadingState(!1)}))}),
d.hitch(this,function(){this._switchLoadingState(!1)}))},closeDropMenu:function(){this.inherited(arguments);this.hideTransNode();this.hideSetVisibilityRangeNode()},_onTransparencyDivClick:function(a){a.stopPropagation()},showTransNode:function(a,c){this.hideSetVisibilityRangeNode();this.transHorizSlider||this._createTransparencyWidget(c);this.transHorizSlider.set("value",1-a);g.set(this.transparencyDiv,"top",this._getTransNodePosition().top);isRTL?g.set(this.transparencyDiv,"left",this._getTransNodePosition().right):
g.set(this.transparencyDiv,"right",this._getTransNodePosition().right);g.set(this.transparencyDiv,"display","block");this.transHorizSlider.focus()},hideTransNode:function(){g.set(this.transparencyDiv,"display","none")},_createTransparencyWidget:function(a){this.transHorizSlider=new w({minimum:0,maximum:1,intermediateChanges:!0},this.transparencyBody);this.own(this.transHorizSlider.on("change",d.hitch(this,function(a){this.emit("onMenuClick",{key:"transparencyChanged"},{newTransValue:a})})));this.own(m(this.transHorizSlider.domNode,
"keydown",d.hitch(this,function(c){c.keyCode===f.ESCAPE?(c.stopPropagation(),c.preventDefault(),this.hideTransNode(),(c=this.getMenuItemNodeByItemKey(a.key))&&k.focus(c)):c.keyCode===f.TAB&&(c.stopPropagation(),c.preventDefault(),this._enableNavMode(c))})));new x({container:"bottomDecoration"},this.transparencyRule)},_onSetVisibilityRangeNode:function(a){a.stopPropagation()},showSetVisibilityRangeNode:function(a,c){this.hideTransNode();if(!this.visibleScaleRangeSlider){var b=a.getScaleRange();this.visibleScaleRangeSlider=
(new z({map:a.map,minScale:b.minScale,maxScale:b.maxScale})).placeAt(this.setVisibilityRangeNode);this.visibleScaleRangeSlider.startup();this._supportsVisibilityRange508Accessibility(c)}this.own(this.visibleScaleRangeSlider.on("scale-range-change",d.hitch(this,function(c){a.setScaleRange(c.minScale,c.maxScale)})));g.set(this.setVisibilityRangeNode,"top",this._getTransNodePosition().top);isRTL?g.set(this.setVisibilityRangeNode,"left",this._getTransNodePosition().right):g.set(this.setVisibilityRangeNode,
"right",this._getTransNodePosition().right);g.set(this.setVisibilityRangeNode,"display","block");this.visibleScaleRangeSlider._slider.focus();this.visibleScaleRangeSlider._slider.focus()},hideSetVisibilityRangeNode:function(){g.set(this.setVisibilityRangeNode,"display","none")},hide:function(){g.set(this.domNode,"display","none")},show:function(){g.set(this.domNode,"display","block")},_enableNavMode:function(a){a.keyCode!==f.TAB||u.isInNavMode()||b.addClass(document.body,"jimu-nav-mode")},_supportsVisibilityRange508Accessibility:function(a){var c=
h(".dijitSliderImageHandle",this.setVisibilityRangeNode)[0],b=h(".dijitDownArrowButton",this.setVisibilityRangeNode),n=b[1],g=b[0],l=b[1];this.own(m(c,"keydown",d.hitch(this,function(a){a.keyCode===f.TAB&&a.shiftKey&&(a.stopPropagation(),a.preventDefault())})));this.own(m(n,"keydown",d.hitch(this,function(a){a.keyCode!==f.TAB||a.shiftKey?a.keyCode===f.ENTER&&(a.stopPropagation(),a.preventDefault(),setTimeout(d.hitch(this,function(){this._bindEsriScaleMenuPopupKey(l)}),200)):(a.stopPropagation(),a.preventDefault())})));
this.own(m(g,"keydown",d.hitch(this,function(a){a.keyCode===f.ENTER&&(a.stopPropagation(),a.preventDefault(),setTimeout(d.hitch(this,function(){this._bindEsriScaleMenuPopupKey(g)}),200))})));this.own(m(g,"click",d.hitch(this,function(a){a.stopPropagation();a.preventDefault();setTimeout(d.hitch(this,function(){this._bindEsriScaleMenuPopupKey(g)}),200)})));this.own(m(l,"click",d.hitch(this,function(a){a.stopPropagation();a.preventDefault();setTimeout(d.hitch(this,function(){this._bindEsriScaleMenuPopupKey(l)}),
200)})));this.own(m(this.setVisibilityRangeNode,"keydown",d.hitch(this,function(c){c.keyCode===f.ESCAPE?(c.stopPropagation(),c.preventDefault(),this.hideSetVisibilityRangeNode(),(c=this.getMenuItemNodeByItemKey(a.key))&&k.focus(c)):c.keyCode===f.TAB?(c.stopPropagation(),this._enableNavMode(c)):c.keyCode===f.ENTER&&c.stopPropagation()})))},_bindEsriScaleMenuPopupKey:function(a){var c=this._getEsriScaleMenuPopup(),e,n,g;c&&(e=h(".dijitInputInner",c)[0],b.setAttr(e,"tabindex","0"),n=h(".esriHeader",
c),g=h(".esriCurrent",c)[0],n[0]&&g&&b.setAttr(e,"aria-label",n[0].innerText+" "+g.innerText),k.focus(e));if(c&&!c._hasBeenBoundKey){var l=h(".esriContent",c)[1];b.setAttr(l,"tabindex","0");n[1]&&b.setAttr(l,"aria-label",n[1].innerText+" ");n=h("li.esriItem",c);p.forEach(n,function(e){b.setAttr(e,"tabindex","0");this.own(m(e,"keydown",d.hitch(this,function(b){var d=this._getMenuItemInfo(c,e);b.keyCode===f.TAB?(b.stopPropagation(),b.preventDefault(),l&&k.focus(l)):b.keyCode===f.DOWN_ARROW?(b.stopPropagation(),
b.preventDefault(),d.nextMenuItem&&k.focus(d.nextMenuItem)):b.keyCode===f.UP_ARROW?(b.stopPropagation(),b.preventDefault(),d.previousMenuItem&&k.focus(d.previousMenuItem)):b.keyCode===f.ESCAPE?(b.stopPropagation(),b.preventDefault(),l&&k.focus(l)):b.keyCode===f.ENTER&&(b.stopPropagation(),b.preventDefault(),b=document.createEvent("MouseEvents"),b.initEvent("click",!0,!0),e.dispatchEvent(b),a&&k.focus(a))})))},this);this.own(m(e,"keydown",d.hitch(this,function(c){c.keyCode===f.TAB?(c.stopPropagation(),
c.preventDefault(),this._enableNavMode(c),k.focus(l)):c.keyCode===f.ESCAPE?a&&k.focus(a):c.keyCode===f.ENTER&&a&&k.focus(a)})));l&&this.own(m(l,"keydown",d.hitch(this,function(b){var d=this._getMenuItemInfo(c);b.keyCode===f.TAB?(b.stopPropagation(),b.preventDefault(),this._enableNavMode(b),k.focus(e)):b.keyCode===f.ENTER?(b.stopPropagation(),b.preventDefault(),d.firstMenuItem&&k.focus(d.firstMenuItem)):b.keyCode===f.ESCAPE&&a&&k.focus(a)})));c._hasBeenBoundKey=!0}},_getMenuItemInfo:function(a,c){var e=
{firstMenuItem:null,lastMenuItem:null,previousMenuItem:null,nextMenuItem:null},f=h("li.esriItem",a),f=p.filter(f,d.hitch(this,function(a){return b.hasClass(a,"esriHidden")?!1:!0}));c&&p.some(f,function(a,b){return a===c?(e.previousMenuItem=f[b-1],e.nextMenuItem=f[b+1],!0):!1},this);e.firstMenuItem=f[0];e.lastMenuItem=f[f.length-1];return e},_getEsriScaleMenuPopup:function(){var a=null;h(".esriScaleMenuPopup",document.body).some(function(c){return"block"===b.getStyle(c,"display")?(a=c,!0):!1});return a}})});