// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("esri/geometry/Point esri/geometry/Polyline esri/geometry/Polygon esri/geometry/webMercatorUtils dojo/Deferred dojo/_base/array dojo/_base/lang esri/geometry/geometryEngine esri/SpatialReference esri/geometry/scaleUtils".split(" "),function(B,x,y,l,C,D,z,d,w,E){var f={getProjectedGeometry:function(b,a,c){var g,e;g=new C;l.canProject(b,a)?(e=l.project(b,a),g.resolve(e)):c.project([b],a,function(a){e=a[0];g.resolve(e)});return g.promise},getDestinationPoint:function(b,a,c){var g=b.x*Math.PI/
180,e=a*Math.PI/180;a=Math.sin(e);var e=Math.cos(e),r=.9966471893352243*Math.tan(b.y*Math.PI/180);b=1/Math.sqrt(1+r*r);var d=r*b,f=Math.atan2(r,e),r=b*a,p=1-r*r,h=2.7233160610984375E11*p/4.040829998465916E13,A=1+h/16384*(4096+h*(-768+h*(320-175*h))),u=h/1024*(256+h*(-128+h*(74-47*h))),k,q,m,t=c/(6356752.314245*A),v,l=0;do h=Math.cos(2*f+t),k=Math.sin(t),q=Math.cos(t),m=u*k*(h+u/4*(q*(-1+2*h*h)-u/6*h*(-3+4*k*k)*(-3+4*h*h))),v=t,t=c/(6356752.314245*A)+m;while(1E-12<Math.abs(t-v)&&200>++l);if(200<=l)return console.error("Formula failed to converge"),
null;c=d*k-b*q*e;c=Math.atan2(d*q+b*k*e,.9966471893352243*Math.sqrt(r*r+c*c));p=2.0955066654848088E-4*p*(4+.003352810664775694*(4-3*p));g=(g+(Math.atan2(k*a,b*q-d*k*e)-.003352810664775694*(1-p)*r*(t+p*k*(h+p*q*(-1+2*h*h))))+3*Math.PI)%(2*Math.PI)-Math.PI;c=180*c/Math.PI;g=180*g/Math.PI;return new B(g,c,new w(4326))},getInverseCalculations:function(b,a){var c=a.x*Math.PI/180-b.x*Math.PI/180,g=.9966471893352243*Math.tan(b.y*Math.PI/180);b=1/Math.sqrt(1+g*g);var g=g*b,e=.9966471893352243*Math.tan(a.y*
Math.PI/180);a=1/Math.sqrt(1+e*e);var e=e*a,d,f,n,p,h,l,u,k,q,m=c,t,v=0;do{d=Math.sin(m);f=Math.cos(m);n=a*d*a*d+(b*e-g*a*f)*(b*e-g*a*f);n=Math.sqrt(n);if(0==n)return 0;p=g*e+b*a*f;h=Math.atan2(n,p);l=b*a*d/n;u=1-l*l;k=p-2*g*e/u;isNaN(k)&&(k=0);q=2.0955066654848088E-4*u*(4+.003352810664775694*(4-3*u));t=m;m=c+.003352810664775694*(1-q)*l*(h+q*n*(k+q*p*(-1+2*k*k)))}while(1E-12<Math.abs(m-t)&&200>++v);if(200<=v)return null;m=2.7233160610984375E11*u/4.040829998465916E13;v=m/1024*(256+m*(-128+m*(74-47*
m)));c=Math.atan2(a*d,b*e-g*a*f);b=Math.atan2(b*d,-g*a+b*e*f);c=(c+2*Math.PI)%(2*Math.PI);b=(b+2*Math.PI)%(2*Math.PI);g=Number((6356752.314245*(1+m/16384*(4096+m*(-768+m*(320-175*m))))*(h-v*n*(k+v/4*(p*(-1+2*k*k)-v/6*k*(-3+4*n*n)*(-3+4*k*k))))).toFixed(3));c=180*c/Math.PI;b=180*b/Math.PI;return{distance:g,initialBearing:c,finalBearing:b}},getLineBetweenPoints:function(b){var a,c=[];D.forEach(b,z.hitch(this,function(a){c.push([a.x,a.y])}));0<c.length&&(a=new x({paths:[c],spatialReference:{wkid:4326}}));
return a},getAngleBetweenPoints:function(b,a){b=f.getInverseCalculations(b,a);return null===b?0:b.initialBearing},getDistanceBetweenPoints:function(b,a){b=f.getInverseCalculations(b,a);return null===b?0:b.distance},getLengthOfGeometry:function(b){var a,c;a={};(c=d.simplify(b))?b.spatialReference.isWebMercator()||4326===b.spatialReference.wkid?(a.meters=d.geodesicLength(c,"meters"),a.miles=d.geodesicLength(c,"miles"),a.kilometers=d.geodesicLength(c,"kilometers"),a.feet=d.geodesicLength(c,"feet")):
(a.meters=d.planarLength(c,"meters"),a.miles=d.planarLength(c,"miles"),a.kilometers=d.planarLength(c,"kilometers"),a.feet=d.planarLength(c,"feet")):(a.meters=0,a.miles=0,a.kilometers=0,a.feet=0);return a},getAreaOfGeometry:function(b){var a,c;a=d.simplify(b);c={};a?b.spatialReference.isWebMercator()||4326===b.spatialReference.wkid?(c.acres=d.geodesicArea(a,"acres"),c.squareMeters=d.geodesicArea(a,"square-meters"),c.squareFeet=d.geodesicArea(a,"square-feet"),c.squareUsFeet=d.geodesicArea(a,109406),
c.squareKilometer=d.geodesicArea(a,"square-kilometers"),c.hectares=d.geodesicArea(a,"hectares"),c.squareMiles=d.geodesicArea(a,"square-miles")):(c.acres=d.planarArea(a,"acres"),c.squareMeters=d.planarArea(a,"square-meters"),c.squareFeet=d.planarArea(a,"square-feet"),c.squareUsFeet=d.planarArea(a,109406),c.squareKilometer=d.planarArea(a,"square-kilometers"),c.hectares=d.planarArea(a,"hectares"),c.squareMiles=d.planarArea(a,"square-miles")):(c.acres=0,c.squareMeters=0,c.squareFeet=0,c.squareUsFeet=
0,c.squareKilometer=0,c.hectares=0,c.squareMiles=0);return c},getPolyLineFromPaths:function(b){var a,c;a=new x(new w({wkid:4326}));for(c=0;c<b.length;c++)a.addPath(b[c]);return a},getPolygonFromPolyLines:function(b,a,c,g){var e,d,f;e=[];g=g?new y(new w(g)):new y(new w({wkid:4326}));for(d=0;d<b.length;d++)for(f=0;f<b[d].length;f++)e.push(b[d][f]);a?e.push(z.clone(e[0])):c&&(e[e.length-1][0]=e[0][0],e[e.length-1][1]=e[0][1]);g.isClockwise(e)||e.reverse();g.addRing(e);return g},getPointsForArc:function(b,
a,c,g){var e,d=[],l,n;e=a-b;a=parseInt(e,10);0>=a&&(a=1);l=Math.abs(e)/Math.abs(a);if(0<l)for(e=0;e<Math.abs(a)+1;e++)n=b+l*e,(n=f.getDestinationPoint(c,n,Math.abs(g)))&&d.push(n);return d},getArcParam:function(b){var a;a={};0>b.distance?0>b.radius?(a.bearing=b.initBearing+90,a.centerPoint=f.getDestinationPoint(b.chordMidPoint,a.bearing,b.centerAndChordDistance),a.startAngle=f.getAngleBetweenPoints(a.centerPoint,b.chordEndPoint),a.endAngle=f.getAngleBetweenPoints(a.centerPoint,b.chordStartPoint)):
(a.bearing=b.initBearing-90,a.centerPoint=f.getDestinationPoint(b.chordMidPoint,a.bearing,b.centerAndChordDistance),a.startAngle=f.getAngleBetweenPoints(a.centerPoint,b.chordStartPoint),a.endAngle=f.getAngleBetweenPoints(a.centerPoint,b.chordEndPoint)):0<b.radius?(a.bearing=b.initBearing+90,a.centerPoint=f.getDestinationPoint(b.chordMidPoint,a.bearing,b.centerAndChordDistance),a.startAngle=f.getAngleBetweenPoints(a.centerPoint,b.chordStartPoint),a.endAngle=f.getAngleBetweenPoints(a.centerPoint,b.chordEndPoint)):
(a.bearing=b.initBearing-90,a.centerPoint=f.getDestinationPoint(b.chordMidPoint,a.bearing,b.centerAndChordDistance),a.startAngle=f.getAngleBetweenPoints(a.centerPoint,b.chordEndPoint),a.endAngle=f.getAngleBetweenPoints(a.centerPoint,b.chordStartPoint));return a},removeNegativeExponents:function(b){return 1<b.toString().toLowerCase().split("e-").length?0:b},getChordLengthFromArcLength:function(b,a){var c;b=Math.abs(b);c=Math.PI*Math.abs(a);a=Math.abs(a)*Math.sin(Math.abs(b)/Math.abs(a)/2);return b<=
c?2*a:-2*a},getArcLengthFromChordLength:function(b,a){var c;c=Math.abs(b);a=Math.abs(a);c=2*Math.asin(c/(2*a))*a;0>b&&(c=2*Math.PI*a-c);return c},chordBearingToTangentBearing:function(b,a,c){var d;d=180/Math.PI*Math.acos(Math.abs(c)/2/Math.abs(a));a/=Math.abs(a);b=b+90*a-c/Math.abs(c)*a*d;return f.removeNegativeExponents(0>b?b+360:360<=b?b%360:b)},tangentBearingToChordBearing:function(b,a,c){var d;d=180/Math.PI*Math.acos(Math.abs(c)/2/Math.abs(a));a/=Math.abs(a);b=b+90*a-c/Math.abs(c)*a*d;return f.removeNegativeExponents(0>
b?b+360:360<=b?b%360:b)},getUnitValueForSR:function(b){switch(E.getUnitValueForSR(b)){case 1:return"meters";case 111194.87428468118:return"meters";case .3048:return"feet";case .3048006096:case .3048006096012192:return"uSSurveyFeet"}},getRotationAngleBetweenPoints:function(b,a){var c,d;b=l.project(b,new w(102100));a=l.project(a,new w(102100));c=a.x-b.x;b=a.y-b.y;a=180*Math.atan2(Math.abs(c),Math.abs(b))/Math.PI;d=180*Math.atan2(Math.abs(b),Math.abs(c))/Math.PI;c=f.removeNegativeExponents(c);b=f.removeNegativeExponents(b);
a=f.removeNegativeExponents(a);d=f.removeNegativeExponents(d);if(0===b){if(0===c)return 0;if(0<c)return 90;if(0>c)return 270}else if(0<b){if(0===c)return 0;if(0<c)return a;if(0>c)return 270+d}else if(0>b){if(0===c)return 180;if(0<c)return 90+d;if(0>c)return 180+a}},getScaleDistanceBetweenPoints:function(b,a){b=l.project(b,new w(102100));a=l.project(a,new w(102100));b=d.distance(b,a,9001);return f.removeNegativeExponents(b)}};return f});