// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/dom-class dojo/dom-construct esri/request jimu/utils".split(" "),function(l,k,f,g,m,h){return l("WeatherInfo",null,{constructor:function(c,a,b){this.container=c;this.parent=b;this.weatherURL=a;this.weatherDict={119:["Cloudy","cloudy5.png","cloudy5.png"],377:["Moderate or heavy showers of ice pellets","hail.png","hail.png"],374:["Light showers of ice pellets","hail.png","hail.png"],350:["Ice pellets","hail.png","hail.png"],353:["Light rain shower","light_rain.png",
"light_rain.png"],302:["Moderate rain","light_rain.png","light_rain.png"],296:["Light rain","light_rain.png","light_rain.png"],293:["Patchy light rain","light_rain.png","light_rain.png"],266:["Light drizzle","light_rain.png","light_rain.png"],263:["Patchy light drizzle","light_rain.png","light_rain.png"],122:["Overcast","overcast.png","overcast.png"],359:["Torrential rain shower","shower3.png","shower3.png"],308:["Heavy rain","shower3.png","shower3.png"],365:["Moderate or heavy sleet showers","sleet.png",
"sleet.png"],362:["Light sleet showers","sleet.png","sleet.png"],320:["Moderate or heavy sleet","sleet.png","sleet.png"],317:["Light sleet","sleet.png","sleet.png"],314:["Moderate or Heavy freezing rain","sleet.png","sleet.png"],311:["Light freezing rain","sleet.png","sleet.png"],284:["Heavy freezing drizzle","sleet.png","sleet.png"],281:["Freezing drizzle","sleet.png","sleet.png"],185:["Patchy freezing drizzle nearby","sleet.png","sleet.png"],182:["Patchy sleet nearby","sleet.png","sleet.png"],395:["Moderate or heavy snow in area with thunder",
"snow4.png","snow4.png"],335:["Patchy heavy snow","snow4.png","snow4.png"],230:["Blizzard","snow4.png","snow4.png"],227:["Blowing snow","snow4.png","snow4.png"],371:["Moderate or heavy snow showers","snow5.png","snow5.png"],338:["Heavy snow","snow5.png","snow5.png"],389:["Moderate or heavy rain in area with thunder","tstorm3.png","tstorm3.png"],392:["Patchy light snow in area with thunder","snow2.png","snow2_night.png"],386:["Patchy light rain in area with thunder","tstorm1.png","tstorm1_night.png"],
368:["Light snow showers","snow2.png","snow2_night.png"],356:["Moderate or heavy rain shower","shower2.png","shower2_night.png"],332:["Moderate snow","snow3.png","snow3_night.png"],329:["Patchy moderate snow","snow2.png","snow2_night.png"],326:["Light snow","snow1.png","snow1_night.png"],323:["Patchy light snow","snow1.png","snow1_night.png"],305:["Heavy rain at times","shower2.png","shower2_night.png"],299:["Moderate rain at times","shower2.png","shower2_night.png"],260:["Freezing fog","fog.png",
"fog_night.png"],248:["Fog","fog.png","fog_night.png"],200:["Thundery outbreaks in nearby","tstorm1.png","tstorm1_night.png"],179:["Patchy snow nearby","snow1.png","snow1_night.png"],176:["Patchy rain nearby","shower1.png","shower1_night.png"],143:["Mist","mist.png","mist_night.png"],116:["Partly Cloudy","cloudy3.png","cloudy3_night.png"],113:["Clear/Sunny","sunny.png","sunny_night.png"]}},updateForIncident:function(c){this.container.innerHTML="";f.add(this.container,"loading");var a=c;"point"!==
c.type&&(a=c.getExtent().getCenter());c=a.y+","+a.x;m({url:"Yahoo"===this.parent._weatherSource?this.weatherURL+"\x26q\x3d"+('select wind,item.condition from weather.forecast where woeid in (select woeid from geo.places(1) where text\x3d"('+c+')")\x26format\x3djson'):this.weatherURL+"\x26q\x3d"+c+"\x26callbackNode\x3dLocalPerspective",callbackParamName:"callback"},{useProxy:!1}).then(k.hitch(this,function(a){return"Yahoo"===this.parent._weatherSource?this._resultsHandlerYahoo(a):this._resultsHandlerDarkSky(a)}),
k.hitch(this,function(){}))},_resultsHandlerYahoo:function(c){var a,b;f.remove(this.container,"loading");if(c.query.results){var e;a=c.query.results.channel.item.condition;c=c.query.results.channel.wind;this.container.innerHTML="";b=g.create("div",{id:"tpc",style:"width: 100%;"},this.container);f.add(b,"IMT_tabPanelContent");if(a){e=1;var d=a.date.split(" "),k=d[5],d=d[4].split(":"),d=parseInt(d[0],10);if("AM"===k){if(6>d||12===d)e=2}else 6<d&&12>d&&(e=2);1===e?this.parent.spillTime.setValue("DY"):
this.parent.spillTime.setValue("NTE");e=a.temp;a=parseInt(a.code,10);a=this.parent.nls.temperature+"\x3cbr/\x3e\x3cimg style\x3d'height:45px' src\x3d'"+this.parent.folderUrl+"images/w/yahoo/"+a+".png' /\x3e\x3cbr/\x3e"+e+"\x26deg;";a=this.parent.config.celsius?a+" "+this.parent.nls.c:a+" "+this.parent.nls.f;a=g.create("div",{innerHTML:h.sanitizeHTML(a)},b);f.add(a,"ERGcolSmall");a=this.parent.nls.wind+"\x3cbr/\x3e\x3cspan style\x3d'font-size: 30px; line-height:47px'\x3e"+"N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW".split(" ")[Math.floor(c.direction/
22.5+.5)%16]+"\x3c/span\x3e\x3cbr/\x3e"+c.speed+" MPH";b=g.create("div",{innerHTML:h.sanitizeHTML(a)},b);f.add(b,"ERGcolSmall");this.parent.windDirection.setValue(parseFloat(c.direction));6>=c.speed?this.parent.windSpeed.setValue("LOW"):6<c.speed&&12>=c.speed?this.parent.windSpeed.setValue("MOD"):this.parent.windSpeed.setValue("HI");this._addCredits(this.parent._weatherSource)}}else this._resetWeatherInfo(this.parent._weatherSource,this.parent.nls.weatherErrorMessage)},_resultsHandlerDarkSky:function(c){var a=
c.data.current_condition;this.container.innerHTML="";f.remove(this.container,"loading");c=g.create("div",{id:"tpc",style:"width: 100%;"},this.container);f.add(c,"IMT_tabPanelContent");var b,e;if(0<a.length){var a=a[0],d=1;b=a.localObsDateTime.split(" ");e=b[2];b=b[1].split(":");b=parseInt(b[0],10);if("AM"===e){if(6>b||12===b)d=2}else 6<b&&12>b&&(d=2);1===d?this.parent.spillTime.setValue("DY"):this.parent.spillTime.setValue("NTE");e=a.temp_F;this.parent.config.celsius&&(e=a.temp_C);b=a.weatherCode;
b=this.weatherDict[parseInt(b,10)];b=this.parent.nls.temperature+"\x3cbr/\x3e\x3cimg style\x3d'height:45px' src\x3d'"+this.parent.folderUrl+"images/w/"+b[d]+"' /\x3e\x3cbr/\x3e"+e+"\x26deg;";b=this.parent.config.celsius?b+" "+this.parent.nls.c:b+" "+this.parent.nls.f;d=g.create("div",{innerHTML:h.sanitizeHTML(b)},c);f.add(d,"ERGcolSmall");d=a.windspeedMiles;b=" MPH";this.parent.config.celsius&&(d=a.windspeedKmph,b=" KMPH");e=a.winddir16Point;b=this.parent.nls.wind+"\x3cbr/\x3e\x3cspan style\x3d'font-size: 30px; line-height:47px'\x3e"+
e+"\x3c/span\x3e\x3cbr/\x3e"+d+b;c=g.create("div",{innerHTML:h.sanitizeHTML(b)},c);f.add(c,"ERGcolSmall");switch(e){case "N":this.parent.windDirection.setValue("180.0");break;case "NNE":this.parent.windDirection.setValue("202.5");break;case "NE":this.parent.windDirection.setValue("225.0");break;case "ENE":this.parent.windDirection.setValue("247.5");break;case "E":this.parent.windDirection.setValue("270.0");break;case "ESE":this.parent.windDirection.setValue("292.5");break;case "SE":this.parent.windDirection.setValue("315.0");
break;case "SSE":this.parent.windDirection.setValue("337.5");break;case "S":this.parent.windDirection.setValue("0.0");break;case "SSW":this.parent.windDirection.setValue("22.5");break;case "SW":this.parent.windDirection.setValue("45.0");break;case "WSW":this.parent.windDirection.setValue("67.5");break;case "W":this.parent.windDirection.setValue("90.0");break;case "WNW":this.parent.windDirection.setValue("112.5");break;case "NW":this.parent.windDirection.setValue("135.0");break;case "NNW":this.parent.windDirection.setValue("157.5")}6>=
a.windspeedMiles?this.parent.windSpeed.setValue("LOW"):6<d&&12>=d?this.parent.windSpeed.setValue("MOD"):this.parent.windSpeed.setValue("HI")}this._addCredits(this.parent._weatherSource)},_resetWeatherInfo:function(c,a){this.container.innerHTML="";var b=g.create("div",{id:"tpc",style:"width: 100%;"},this.container);f.add(b,"IMT_tabPanelContent");var e=g.create("div",{innerHTML:h.sanitizeHTML("\x3cimg style\x3d'height:76px' src\x3d'"+this.parent.folderUrl+"images/w/dunno.png' /\x3e")},b);f.add(e,"ERGcolSmallUnknown");
a=g.create("div",{innerHTML:h.sanitizeHTML("\x3cspan\x3e"+a+"\x3c/span\x3e")},b);f.add(a,"ERGcolSmall");this._addCredits(c)},_addCredits:function(c){c="Yahoo"===c?"\x3ca style\x3d'color:#6e6e6e;text-decoration:none'href\x3d'https://www.yahoo.com/news/weather/' title\x3d'Yahoo Weather' target\x3d'_blank'\x3e\x3cimg style\x3d'height:36px;margin-top: 10px;' src\x3d'"+this.parent.folderUrl+'images/yahoo.png\' /\x3e\x3cbr /\x3e\x3cspan style\x3d"font-size:11px;color:#6e6e6e"\x3ePowered by\x3cbr/\x3eYahoo\x3c/a\x3e\x3c/span\x3e':
"\x3ca style\x3d'color:#6e6e6e;text-decoration:none'href\x3d'https://darksky.net/poweredby/' title\x3d'Dark Sky' target\x3d'_blank'\x3e\x3cimg style\x3d'height:36px;margin-top: 10px;' src\x3d'"+this.parent.folderUrl+'images/darksky.png\' /\x3e\x3cbr /\x3e\x3cspan style\x3d"font-size:11px;color:#6e6e6e"\x3ePowered by\x3cbr/\x3eDark Sky\x3c/a\x3e\x3c/span\x3e';var a=g.create("div",{id:"tpc",style:"width: 100%;"},this.container);f.add(a,"IMT_tabPanelContent");c=g.create("div",{innerHTML:h.sanitizeHTML(c)},
a);f.add(c,"ERGcolSmall");f.add(c,"ERGcolLast")},_errorHandler:function(){f.remove(this.container,"loading")}})});