// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/Deferred jimu/BaseWidgetSetting esri/tasks/query esri/tasks/QueryTask esri/geometry/Extent esri/geometry/geometryEngine esri/SpatialReference esri/geometry/webMercatorUtils dojo/_base/array".split(" "),function(r,m,n,t,u,v,w,p,q,x,y){return r([t],{baseClass:"jimu-widget-smartEditor-widgets-intersection",layerFieldsObj:{},queriedLayers:[],layersInvolvedInIgnoreLayerRanking:[],maxToleranceForlayer:{},maxToleranceForlayerInPx:{},completeFeatures:{},postCreate:function(){this.startup();
this.layerFieldsObj={};this.queriedLayers=[];this.maxToleranceForlayer={};this.maxToleranceForlayerInPx={};this.layersInvolvedInIgnoreLayerRanking=[];this.completeFeatures=[]},startup:function(){},_canGetGeodesicBuffers:function(a){var b;b=new q(4326);return a&&x.canProject(a,b)?!0:!1},_getbufferedGeometry:function(a,b){return(a=this._canGetGeodesicBuffers(a)?p.geodesicBuffer([a],[b],"meters",!0):p.buffer([a],[b],"meters",!0))&&0<a.length?a[0]:null},getToleranceValueInMeters:function(a){var b;b=0;
a&&(a.useDefault?(b=this.defaultToleranceSettings.value,a=this.defaultToleranceSettings.unit):(b=a.value,a=a.unit),b=this.convertToMeters(b,a));return b},setMaxToleranceForLayer:function(a,b){var c;c=this.getToleranceValueInMeters(b);if(b&&"px"===b.unit&&!b.useDefault){if(b=b.value,!this.maxToleranceForlayerInPx.hasOwnProperty(a)||this.maxToleranceForlayerInPx[a]<b)this.maxToleranceForlayerInPx[a]=b}else 0<c&&(!this.maxToleranceForlayer.hasOwnProperty(a)||this.maxToleranceForlayer[a]<c)?this.maxToleranceForlayer[a]=
c:0===c&&(b=this.defaultPixelsTolerance,!this.maxToleranceForlayerInPx.hasOwnProperty(a)||this.maxToleranceForlayerInPx[a]<b)&&(this.maxToleranceForlayerInPx[a]=b)},convertToMeters:function(a,b){var c=a;switch(b){case "meters":c=a;break;case "feet":c=.3048*a;break;case "kilometers":c=1E3*a;break;case "miles":c=1609.34*a}return c},getDistinctLayers:function(a,b){var c,d,f;d=new n;c=new n;f={};this.layerFieldsObj={};this.queriedLayers=[];this.ignoreLayerRanking=!1;this.drawnGeometry=b;if(a.fieldValues){for(var e in a.fieldValues){f[e]=
[];for(var g=0;g<a.fieldValues[e].length;g++){var h=a.fieldValues[e][g];if("Intersection"===h.actionName&&h.enabled){h.ignoreLayerRanking&&(this.ignoreLayerRanking=!0);for(var k=0;k<h.fields.length;k++){var l=h.fields[k];-1===f[e].indexOf(l.layerId)&&f[e].push(l.layerId);-1===this.layersInvolvedInIgnoreLayerRanking.indexOf(l.layerId)&&h.ignoreLayerRanking&&this.layersInvolvedInIgnoreLayerRanking.push(l.layerId);this.setMaxToleranceForLayer(l.layerId,l.toleranceSettings)}}}}this._getIntersectionsForEachField(f,
b,c)}else c.resolve({});c.then(m.hitch(this,function(){var b={};if(a.fieldValues)for(var c in a.fieldValues){b[c]={};for(var e=0;e<a.fieldValues[c].length;e++){var f=a.fieldValues[c][e];if("Intersection"===f.actionName&&f.enabled)if(f.ignoreLayerRanking)b[c]=this._getClosestFeature(f.fields);else for(var k=0;k<f.fields.length;k++){var g,l,h;l=f.fields[k];h=l.layerId;if(!b[c].hasOwnProperty(h)&&(g=this._getProcessedFeature(h,l.toleranceSettings))){f={};f[l.field]=g[l.field];b[c][h]=f;break}}}}d.resolve(b)}));
return d.promise},_getIntersectingFeatures:function(a,b){var c,d,f,e;c=[];f=0;if(this.completeFeatures.hasOwnProperty(a)&&(e=this.completeFeatures[a],b&&"px"!==b.unit&&(f=this.getToleranceValueInMeters(b)),0<e.length&&(f?d=this._getbufferedGeometry(this.drawnGeometry,f):this.maxToleranceForlayer.hasOwnProperty(a)&&this.maxToleranceForlayer[a]||this.maxToleranceForlayerInPx.hasOwnProperty(a)&&this.maxToleranceForlayerInPx[a]?d="point"===this.drawnGeometry.type?this.maxToleranceForlayerInPx.hasOwnProperty(a)?
this.pointToExtent(this.map,this.drawnGeometry,this.maxToleranceForlayerInPx[a]):this.pointToExtent(this.map,this.drawnGeometry,this.defaultPixelsTolerance):this.drawnGeometry:c=e,d)))for(a=0;a<e.length;a++)b=e[a],b.geometry&&p.intersects(d,b.geometry)&&c.push(b);return c},_getClosestFeature:function(a){var b,c,d,f,e,g=[],h;b={};for(f=0;f<a.length;f++){var k=[];d=a[f].layerId;k=this._getIntersectingFeatures(d,a[f].toleranceSettings);for(e=0;e<k.length;e++)this.drawnGeometry&&k[e].geometry&&(k[e].distanceToLocation=
p.distance(this.drawnGeometry,k[e].geometry,"meters")),k[e].layerId=d,k[e].fields?k[e].fields.push(a[f].field):k[e].fields=[a[f].field];g=g.concat(k)}0<g.length&&(g.sort(function(a,b){return a.distanceToLocation<b.distanceToLocation?-1:a.distanceToLocation>b.distanceToLocation?1:0}),c=g[0].attributes,a=this._jimuLayerInfos.getLayerOrTableInfoById(g[0].layerId).layerObject,c.esriCTUseLayerName=a.name,h={},y.forEach(g[0].fields,function(a){h[a]=c[a]}),b[g[0].layerId]=h);return b},_getProcessedFeature:function(a,
b){var c,d;d=[];d=this._getIntersectingFeatures(a,b);0<d.length&&(c=d[0].attributes,a=this._jimuLayerInfos.getLayerOrTableInfoById(a).layerObject,c.esriCTUseLayerName=a.name);return c},_getIntersectionsForEachField:function(a,b,c){var d,f;d=Object.keys(a);f=0;this.maxToleranceForlayer&&(f=Object.keys(this.maxToleranceForlayer).length);if(0<d.length){var e=d[0];(this.ignoreLayerRanking||0<f?this._asyncIntersectionRequests(a[e],b):this._syncIntersectionRequests(a[e],b)).then(m.hitch(this,function(){this.ignoreLayerRanking||
0<f?a[e]&&0===a[e].length&&delete a[e]:delete a[e];this._getIntersectionsForEachField(a,b,c)}))}else c.resolve()},_filterQueriedLayers:function(a){for(var b in this.layerFieldsObj){var c=a.indexOf(b);-1<c&&a.splice(c,1)}return a},_asyncIntersectionRequests:function(a,b,c){c||(c=new n);a=this._filterQueriedLayers(a);0<a.length?this._getIntersectedFeatures(a[0],b).then(m.hitch(this,function(d){a.splice(0,1);0<a.length?(this._asyncIntersectionRequests(a,b,c),this._intersectionResult(d)):this._intersectionResult(d,
c)})):c.resolve();return c.promise},_syncIntersectionRequests:function(a,b,c){c||(c=new n);a=this._filterQueriedLayers(a);0<a.length?this._getIntersectedFeatures(a[0],b).then(m.hitch(this,function(d){0<d.features.length?this._intersectionResult(d,c):(a.splice(0,1),0<a.length?this._syncIntersectionRequests(a,b,c):this._intersectionResult(d,c))})):c.resolve();return c.promise},_intersectionResult:function(a,b){a.layerId&&(this.layerFieldsObj[a.layerId]={},a.features&&0<a.features.length&&(this.layerFieldsObj[a.layerId]=
a.featuresAttributes));b&&b.resolve()},pointToExtent:function(a,b,c){if(0===c)return b;var d=a.extent.getWidth()/a.width;c*=d;return new w(b.x-c,b.y-c,b.x+c,b.y+c,a.spatialReference)},_getAppropriateGeometryForQuery:function(a,b){var c;this.maxToleranceForlayer.hasOwnProperty(a)?c=this._getbufferedGeometry(b,this.maxToleranceForlayer[a]):(c=b,"point"===b.type&&(c=this.maxToleranceForlayerInPx.hasOwnProperty(a)?this.pointToExtent(this.map,b,this.maxToleranceForlayerInPx[a]):this.pointToExtent(this.map,
b,this.defaultPixelsTolerance)));return c},_getIntersectedFeatures:function(a,b){var c,d,f,e,g,h;c=new n;if(this._jimuLayerInfos.getLayerOrTableInfoById(a))g=this._jimuLayerInfos.getLayerOrTableInfoById(a).layerObject;else return c.resolve({layerId:a,features:[],featuresAttributes:{}}),c.promise;h=g.objectIdField;d=new u;f=new v(g.url);d.geometry=this._getAppropriateGeometryForQuery(a,b);d.outFields=["*"];if(g=g.getDefinitionExpression())d.where=g;-1<this.layersInvolvedInIgnoreLayerRanking.indexOf(a)||
this.maxToleranceForlayer.hasOwnProperty(a)||this.maxToleranceForlayerInPx.hasOwnProperty(a)?(d.returnGeometry=!0,d.outSpatialReference=new q(b.spatialReference.toJson())):d.returnGeometry=!1;f.execute(d,m.hitch(this,function(b){b&&b.features&&0<b.features.length?(b.features.sort(function(a,b){a=parseInt(a.attributes[h],10);b=parseInt(b.attributes[h],10);return a<b?1:0}),e=b.features[0].attributes):(b={features:[]},e={});this.completeFeatures[a]=b.features;c.resolve({layerId:a,features:b.features,
featuresAttributes:e})}),m.hitch(this,function(){this.completeFeatures[a]=[];c.resolve({layerId:a,features:[],featuresAttributes:{}})}));return c.promise}})});