// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array esri/geometry/Extent jimu/utils esri/dijit/AttributeInspector".split(" "),function(m,g,h,n,k,p){var f={};f.ATI=m([p],{constructor:function(){this._aiConnects=[];this._selection=[];this._toolTips=[]}});f.checkIfFieldAliasAlreadyExists=function(a,c){return 0<=a.split(",").indexOf(c)};f.pointToExtent=function(a,c,b){var d=a.extent.getWidth()/a.width;b*=d;return new n(c.x-b,c.y-b,c.x+b,c.y+b,a.spatialReference)};f.filterOnlyUpdatedAttributes=
function(a,c,b){if(null===c||void 0===c)return a;var d={},e;for(e in a)a.hasOwnProperty(e)&&(e===b.objectIdField||e===b.globalIdField?d[e]=a[e]:null===a[e]&&""===c[e]||a[e]===c[e]||(d[e]=a[e]));return d};f.mergeFieldInfosWithConfiguration=function(a,c){var b=[],d=this.getDefaultEditableFieldInfos(a,!1);c&&c.fieldInfos?(h.forEach(c.fieldInfos,function(a){h.some(d,function(c){if(a.fieldName===c.fieldName)return b.push(this.mergeLastToFirst(c,a)),!0},this)},this),h.forEach(d,function(a){0===h.filter(b,
function(c){return c.fieldName===a.fieldName},this).length&&b.push(a)},this)):b=d;var e=[];a.layerObject.hasOwnProperty("globalIdField")&&void 0!==a.layerObject.globalIdField&&null!==a.layerObject.globalIdField&&e.push(a.layerObject.globalIdField);a.layerObject.hasOwnProperty("objectIdField")&&void 0!==a.layerObject.objectIdField&&null!==a.layerObject.objectIdField&&e.push(a.layerObject.objectIdField);if(a.layerObject.hasOwnProperty("editFieldsInfo")&&void 0!==a.layerObject.editFieldsInfo&&null!==
a.layerObject.editFieldsInfo)for(var l in a.layerObject.editFieldsInfo)a.layerObject.editFieldsInfo.hasOwnProperty(l)&&e.push(a.layerObject.editFieldsInfo[l]);return b=b.filter(function(a){return-1!==h.indexOf(e,a.fieldName)?!1:a.isEditableOnLayer})};f.getDefaultEditableFieldInfos=function(a,c){var b=[],d=this.getFieldInfosFromWebmap(a);a=this.getFieldInfosLayer(a);if(void 0===d||null===d)d=a;else{var e=[];h.forEach(a,function(a){0===h.filter(d,function(c){return c.name===a.fieldName}).length&&(a.isEditableOnLayer=
a.editable,e.push(a))});0<e.length&&(d=d.concat(e))}h.forEach(d,function(a){!1===a.hasOwnProperty("isEditableOnLayer")&&(a.isEditableOnLayer=a.editable);!1===a.editable&&(a.isEditable=a.editable);!1===a.isEditable&&(a.editable=a.isEditable);a.fieldName=a.name;!0===a.editable&&!0===c?b.push(g.clone(a)):!1===c&&b.push(g.clone(a))});return b};f.updatePopupDateFormat=function(a){var c={shortDate:{datePattern:"M/d/y"},shortDateLE:{datePattern:"d/M/y"},longMonthDayYear:{datePattern:"MMMM d, y"},dayShortMonthYear:{datePattern:"d MMM y"},
longDate:{datePattern:"EEEE, MMMM d, y",selector:"date"},shortDateShortTime:{datePattern:"M/d/y",timePattern:"h:mm a",timeEnabled:!0},shortDateLEShortTime:{datePattern:"d/M/y",timePattern:"h:mm a",timeEnabled:!0},shortDateShortTime24:{datePattern:"M/d/y",timePattern:"H:mm",timeEnabled:!0},shortDateLEShortTime24:{datePattern:"d/M/y",timePattern:"H:mm",timeEnabled:!0},shortDateLongTime:{datePattern:"M/d/y",timePattern:"h:mm:ss a",timeEnabled:!0},shortDateLELongTime:{datePattern:"d/M/y",timePattern:"h:mm:ss a",
timeEnabled:!0},shortDateLongTime24:{datePattern:"M/d/y",timePattern:"H:mm:ss",timeEnabled:!0},shortDateLELongTime24:{datePattern:"d/M/y",timePattern:"H:mm:ss",timeEnabled:!0},longMonthYear:{datePattern:"MMMM y"},shortMonthYear:{datePattern:"MMM y"},year:{datePattern:"y"}},b="",d;for(d in c)if(k.isEqual(a,c[d])){b=d;break}return b};f.getFieldInfosFromWebmap=function(a){var c=null,b=a.getPopupInfo();b&&b.fieldInfos&&(c=[],h.forEach(b.fieldInfos,function(b){h.some(a.layerObject.fields,function(a){if(a.name===
b.fieldName)return a=this.mergeFirstToLast(b,a),a.format&&a.format.dateFormat&&(a.format.dateFormat.hasOwnProperty("datePattern")||a.format.dateFormat.hasOwnProperty("timePattern"))&&(a.format.dateFormat=this.updatePopupDateFormat(a.format.dateFormat)),a.format&&a.format.dateFormat&&a.format.dateFormat.toLowerCase()&&0<=a.format.dateFormat.toLowerCase().indexOf("time")&&(a.format.time=!0),c.push(a),!0},this)},this));return c};f.getFieldInfosLayer=function(a){var c=[];a&&a.layerObject&&h.forEach(a.layerObject.fields,
function(a){var b=k.getDefaultPortalFieldInfo(a),b=this.mergeFirstToLast(b,a);b.format&&b.format.dateFormat&&(b.format.dateFormat.hasOwnProperty("datePattern")||b.format.dateFormat.hasOwnProperty("timePattern"))&&(b.format.dateFormat=this.updatePopupDateFormat(b.format.dateFormat));b.format&&b.format.dateFormat&&b.format.dateFormat.toLowerCase()&&0<=b.format.dateFormat.toLowerCase().indexOf("time")&&(b.format.time=!0);b.visible=!0;c.push(b)},this);return c};f.getConfigInfos=function(a,c,b,d,e){var f=
[],g=a.getLayerInfoArrayOfWebmap(),k=[];e&&(k=a.getTableInfoArrayOfWebmap(),g=g.concat(k));h.forEach(g,function(a){var e=!1;"Table"!==a.layerObject.type&&"Feature Layer"!==a.layerObject.type||!a.layerObject.url||(a.layerObject.isEditable&&a.layerObject.isEditable()&&b?e=!0:void 0!==b&&!1===b&&(e=!0));if(!0===e){var g=this.getConfigInfo(a,c);g.layerInfo=a;!0===g.featureLayer.layerAllowsDelete&&!1===g.featureLayer.layerAllowsCreate&&!1===g.featureLayer.layerAllowsUpdate?console.warn(g.layerInfo.title+
" delete only not supported"):d&&!0===d?!0===h.some(c,function(a){return a.featureLayer.id===g.featureLayer.id})&&f.push(g):f.push(g)}},this);return f};f.getConfigInfo=function(a,c){var b=null,d=this.createDefaultConfigInfo(a);!1===h.some(c,function(c){return c.featureLayer&&c.featureLayer.id===a.layerObject.id?(b=g.clone(c),b.fieldInfos=this.mergeFieldInfosWithConfiguration(a,b),b=this.mergeDefaultWithConfig(b,d),!0):!1},this)&&(b=d);return b};f.mergeDefaultWithConfig=function(a,c){a.featureLayer=
c.featureLayer;!0===a.allowDelete&&!1===a.featureLayer.layerAllowsDelete&&(a.allowDelete=!1);!1===a.disableGeometryUpdate&&!1===a.featureLayer.layerAllowGeometryUpdates&&(a.disableGeometryUpdate=!0);!1===a.featureLayer.layerAllowsCreate&&!0===a.featureLayer.layerAllowsUpdate&&(a.allowUpdateOnly=!0);return a};f.createDefaultConfigInfo=function(a){var c=!1,b=!1,d=!1,e=!1;try{var f=a.layerObject.getEditCapabilities();f.canCreate&&(c=!0);f.canUpdate&&(e=b=!0);f.canDelete&&(d=!0)}catch(q){a.layerObject.hasOwnProperty("capabilities")&&
(-1===String(a.layerObject.capabilities).indexOf("Update")&&-1===String(a.layerObject.capabilities).indexOf("Delete")&&-1===String(a.layerObject.capabilities).indexOf("Create")&&-1!==String(a.layerObject.capabilities).indexOf("Editing")?c=d=b=!0:(-1!==String(a.layerObject.capabilities).indexOf("Update")&&(e=b=!0),-1!==String(a.layerObject.capabilities).indexOf("Delete")&&(d=!0),-1!==String(a.layerObject.capabilities).indexOf("Create")&&(c=!0)))}a.layerObject.hasOwnProperty("allowGeometryUpdates")&&
(e=a.layerObject.allowGeometryUpdates);"Table"===a.layerObject.type&&a.layerObject.url&&a.getCapabilitiesOfWebMap()&&(b=a.getCapabilitiesOfWebMap(),a.layerObject.isEditable&&a.layerObject.isEditable()&&b&&-1<b.toLowerCase().indexOf("editing")?b=!0:d=b=c=!1,e=!1);return{featureLayer:{id:a.layerObject.id,layerAllowsCreate:c,layerAllowsUpdate:b,layerAllowsDelete:d,layerAllowGeometryUpdates:e},disableGeometryUpdate:!e,allowUpdateOnly:!c,allowDelete:!1,fieldInfos:this.mergeFieldInfosWithConfiguration(a,
null),_editFlag:c||b?!0:!1}};f.mergeLastToFirst=function(){for(var a={},c=0,b=arguments.length,d;c<b;c++)for(d in arguments[c])arguments[c].hasOwnProperty(d)&&(a[d]=arguments[c][d]);return a};f.mergeFirstToLast=function(){for(var a={},c=arguments.length-1,b;0<=c;c--)for(b in arguments[c])arguments[c].hasOwnProperty(b)&&(a[b]=arguments[c][b]);return a};f.isObjectEmpty=function(a){if(a)for(var c in a)if(a.hasOwnProperty(c))return!1;return!0};f.addDateTimeFormat=function(a){a&&a.format&&null!==a.format&&
a.format.dateFormat&&null!==a.format.dateFormat&&0<=a.format.dateFormat.toString().toUpperCase().indexOf("TIME")&&(a.format.time=!0)};f.isDuplicateGroupName=function(a,c){var b=!1;h.some(c,g.hitch(this,function(c){if(a.toLowerCase()===c.toLowerCase())return b=!0}));return b};return f});