// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/DataAggregation/js/UI/templates/FeatureToolbar.html":'\x3cdiv class\x3d"float-right no-select"\x3e\r\n  \x3ctable class\x3d"control-table table-layout" cellpading\x3d"0"\x3e\r\n    \x3ctbody\x3e\r\n      \x3ctr class\x3d"feature-toolbar-row"\x3e\r\n        \x3ctd title\x3d"${nls.featureToolbar.cancel}"\x3e\r\n          \x3cdiv data-dojo-attach-point\x3d"cancelButton" role\x3d"button" tabindex\x3d"-1" class\x3d"bg-ft-img bg-cancel feature-toolbar-btn" \r\n          aria-label\x3d"${nls.featureToolbar.cancel}" data-dojo-attach-event\x3d"onclick:_cancel, onkeydown:_cancel"\x3e\x3c/div\x3e\r\n        \x3c/td\x3e\r\n        \x3ctd title\x3d"${nls.featureToolbar.save}"\x3e\r\n          \x3cdiv  data-dojo-attach-point\x3d"saveButton" role\x3d"button" tabindex\x3d"-1" class\x3d"float-right bg-ft-img bg-save feature-toolbar-btn"\r\n          aria-label\x3d"${nls.featureToolbar.save}" data-dojo-attach-event\x3d"onclick:_save, onkeydown:_save"\x3e\x3c/div\x3e\r\n        \x3c/td\x3e\r\n      \x3c/tr\x3e\r\n    \x3c/tbody\x3e\r\n  \x3c/table\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/Evented dojo/query dojo/dom-class dojo/dom-attr dojo/dom-construct dojo/Deferred dijit/_WidgetBase dijit/_TemplatedMixin dojo/on dojo/keys dojox/gfx/fx dojo/text!./templates/FeatureToolbar.html esri/toolbars/edit jimu/dijit/Message jimu/dijit/Popup jimu/portalUtils jimu/utils esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/Color esri/graphic esri/geometry/webMercatorUtils esri/request".split(" "),function(y,d,l,z,
q,t,g,A,n,B,C,p,m,D,E,F,r,G,u,v,w,x,H,I,J,K){return y([B,C,z],{templateString:E,baseClass:"cf-feature-toolbar",declaredClass:"FeatureToolbar",label:"FeatureToolbar",parent:null,nls:null,map:null,appConfig:null,config:null,feature:null,layer:null,theme:"",locators:[],styleColor:"",featureView:null,_editToolbar:null,csvStore:null,_isAddressFeature:!0,_stageLayer:null,constructor:function(a){d.mixin(this,a);this._syncDisabled=this._locateDisabled=this._cancelDisabled=this._saveDisabled=!0;this._hasAttributeEdit=
!1;this.own(p(this.featureView,"attribute-change",d.hitch(this,this._attributeChange)));this._hasAddressEdit=!1;this.own(p(this.featureView,"address-change",d.hitch(this,this._addressChange)));this._hasGeometryEdit=!1;this.own(p(this._editToolbar,"graphic-move-stop",d.hitch(this,this._graphicMoveStop)));this.own(p(this.featureView,"address-located",d.hitch(this,this._graphicMoveStop)));this.locator=this._getLocator(0);this._initOriginalValues()},postCreate:function(){this.inherited(arguments)},startup:function(){this.inherited(arguments);
this._started=!0;this.updateImageNodes()},_getLocator:function(a){for(var c;a<this.csvStore._geocodeSources.length;a++)if(this.locatorSource=this.csvStore._geocodeSources[a],this.locatorSource.locator.locationToAddress){c=this.locatorSource.locator;this._locatorIndex=a;break}c&&(c.outSpatialReference=this.map.spatialReference,c.countryCode=this.locatorSource.countryCode);return c},_initOriginalValues:function(){this._originalValues=d.clone(this.featureView.feature)},_attributeChange:function(a){this._hasAttributeEdit=
a;this.featureView.isDuplicate&&this.featureView._useGeomFromLayer?this._updateSaveAndCancel(!this._hasAttributeEdit):this._updateSaveAndCancel(!(this._hasAttributeEdit||this._hasGeometryEdit));this._updateSync(!this.featureView._validateAddressDifference())},_addressChange:function(a){this._hasAddressEdit=a;this._updateLocate(!a)},_graphicMoveStop:function(a){this.featureView.isShowing&&(this._hasGeometryEdit=!0,this.featureView.isDuplicate&&this.featureView._useGeomFromLayer?this._updateSaveAndCancel(!this._hasAttributeEdit):
this._updateSaveAndCancel(!(this._hasAttributeEdit||this._hasGeometryEdit)),this.map.infoWindow.setFeatures(this.featureView._feature),this.map.infoWindow.select(0),a?this._reverseLocate(a.graphic.geometry).then(d.hitch(this,function(){this._hasAddressEdit=!0;this._updateLocate(!0);this.featureView._validateAddressDifference()&&this._updateSync(!1);this.locator=this._getLocator(0)}),function(a){this.locator=this._getLocator(0);new r(a)}):this.featureView._validateAddressDifference()&&this._updateSync(!1))},
_reverseLocate:function(a){var c=new n;if(this._isAddressFeature){var b=this.parent.portal?this.parent.portal:this.appConfig.portalUrl?u.getPortal(this.appConfig.portalUrl):null,e=this.locatorSource&&this.locatorSource.isEsriLocator;K({url:this.locator.url+"/reverseGeocode",content:{f:"json",location:JSON.stringify(a),distance:100,outSR:JSON.stringify(a.spatialReference),forStorage:e?this.featureView.isDuplicate&&!this.featureView.isDuplicateLocated||this.featureView.isUnMatched&&!this.featureView.isUnMatchedLocated:
!1,token:e?b&&b.credential&&b.credential.token?b.credential.token:null:null},callbackParamName:"callback"}).then(d.hitch(this,function(a){this.featureView._updateAddressFields(a.address,!1);c.resolve({address:a.address})}),d.hitch(this,function(b){this._getNextLocator()?this._reverseLocate(a).then(function(a){c.resolve(a)}):(this.featureView._updateAddressFields({},!1),c.reject({message:b.message}))}))}else a.spatialReference.isWebMercator&&a.spatialReference.isWebMercator()&&(b=J.webMercatorToGeographic(a)),
this.featureView._updateAddressFields(b||a,!1),c.resolve({geometry:a});return c},_enableEdit:function(){this._editToolbar.activate(F.MOVE,this.featureView._feature)},_disableEdit:function(){this._editToolbar.deactivate()},_undoEdits:function(){this._hasAttributeEdit&&(this.featureView.resetAttributeValues(),this._hasAttributeEdit=!1);this._hasAddressEdit&&(this.featureView.resetAddressValues(this._originalValues),this._hasAddressEdit=!1);this._hasGeometryEdit?(this.featureView.resetGeometry(this._originalValues.geometry),
this._hasGeometryEdit=!1):this.featureView.resetFromLayerRows();this._updateSync(!this.featureView._validateAddressDifference());this._updateLocate(!0)},_locate:function(a){if("keydown"!==a.type||a.keyCode===m.ENTER||a.keyCode===m.SPACE)this._locateDisabled||this._locateFeature().then(d.hitch(this,function(){this._hasAddressEdit=!1;this._updateLocate(!0)}))},_cancel:function(a){if(("keydown"!==a.type||a.keyCode===m.ENTER||a.keyCode===m.SPACE)&&!this._cancelDisabled)var c=new G({titleLabel:this.nls.featureToolbar.cancelTitle,
width:400,autoHeight:!0,content:A.create("div",{innerHTML:this.nls.featureToolbar.cancelMessage,style:"padding-bottom: 10px;"}),buttons:[{label:this.nls.yes,onClick:d.hitch(this,function(){c.close();c=null;this._undoEdits();this._updateSaveAndCancel(!0);this._panToAndSelectFeature(this.featureView.isDuplicate&&this.featureView._useGeomFromLayer?this.featureView._editFeature:this.featureView._feature)})},{label:this.nls.no,onClick:d.hitch(this,function(){c.close()})}],onClose:d.hitch(this,function(){c=
null})})},_save:function(a,c){if("keydown"!==a.type||a.keyCode===m.ENTER||a.keyCode===m.SPACE){var b=this.featureView._feature;if(!this._saveDisabled||!0===c){!0!==c&&(this._setFieldValues(this.featureView),this._setAddressValues(this.featureView),this.featureView.feature.geometry=b.geometry,this._originalValues.geometry=b.geometry,this.featureView.isDuplicate&&(this._originalValues.duplicateGeometry=b.geometry));if(-1===this.featureView.label.indexOf("UnMatched")&&-1===this.featureView.label.indexOf("DuplicateFeatures"))this._updateLayer(this._stageLayer,
null,[b],null,!0,!1).then(d.hitch(this,function(a){a&&"success"===a.status&&this._updateFeatureListLabel(b)}));else if(this.featureView.isDuplicate&&!0!==c)this.featureView._updateDuplicateAttributes(null,!0),this._updateLayer(this.layer,null,[b],null,!0,!1).then(d.hitch(this,function(a){a&&"success"===a.status&&this._updateFeatureListLabel(b)}));else{var e=b.attributes[this.layer.objectIdField];this._updateLayer(this.layer,null,null,[b],!0,!1).then(d.hitch(this,function(a){a&&"success"===a.status&&
this.featureView._parentFeatureList.removeFeature(this.featureView.feature,e).then(d.hitch(this,function(){l.forEach(this.featureView._skipFields,d.hitch(this,function(a){delete b.attributes[a]}));this._updateLayer(this._stageLayer,[b],null,null,!0,!1).then(d.hitch(this,function(a){a&&"success"===a.status&&(a.hasOwnProperty("objectId")&&(this.featureView.feature.fieldInfo.filter(d.hitch(this,function(a){return a.name===this._stageLayer.objectIdField}))[0].value=a.objectId),this.featureView.feature.label=
b.attributes[this.csvStore.labelField],a=this.parent._pageContainer.getViewByTitle("Review"),a.matchedFeatureList.addFeature(this.featureView.feature),a.matchedFeatureList.resetFeatureList(),a._updateReviewRows(!0===c?"duplicate":"unmatched"))}))}))}))}!0!==c&&this._updateSaveAndCancel(!0)}}},_updateFeatureListLabel:function(a){var c=this.csvStore.labelField;a=a.attributes[c];var b=v.stripHTML(a.toString?a.toString():"");b!==this.featureView.featureListLabel.innerHTML&&("."!==this.csvStore.decimalSeperator&&
(a=this.feature.fieldInfo.filter(function(a){return a.name===c&&a.needsFormat&&-1===[null,void 0].indexOf(b)}))&&a.hasOwnProperty("length")&&0<a.length&&(b=v.localizeNumber(b),a[0].formattedValue=b),this.featureView.featureListLabel.innerHTML=b,this.featureView.pageTitleDiv.innerHTML=b)},_updateLayer:function(a,c,b,e,h,f){var k=new n;a.applyEdits(c,b,e).then(d.hitch(this,function(a){var c={status:"success"};this.featureView.isDuplicate&&(this._hasGeometryEdit&&this.featureView._useGeomFromFile&&(this._fileGeometryModified=
!0),this._hasAttributeEdit&&this.featureView._useValuesFromFile&&(this._fileValuesModified=!0));h&&(this._hasAttributeEdit=this._hasGeometryEdit=!1);a&&a.hasOwnProperty("length")&&0<a.length&&a[0].hasOwnProperty("objectId")&&(c.objectId=a[0].objectId);!f&&b&&b.hasOwnProperty("length")&&0<b.length&&(a=this.featureView.parent._pageContainer.getViewByTitle("Review"),a._updateNode(a.submitButton,!0));k.resolve(c)}),d.hitch(this,function(a){new r({message:this.nls.warningsAndErrors.saveError});k.resolve({status:"error",
error:a})}));return k},_setFieldValues:function(a){var c=a._useValuesFromFile,b=c?a._changedFileAttributeRows:a._changedLayerAttributeRows,e=a._feature,h=a.feature;l.forEach(a.featureControlTable.rows,function(a){if(a.isEditRow&&-1<b.indexOf(a.rowIndex)||a.parent&&a.parent.isDuplicate&&!c){var f=a.parent.isDuplicate&&!c?a.layerValueTextBox:a.fileValueTextBox;e.attributes[a.fieldName]=f.value;h.fieldInfo.filter(function(b){return b.name===a.fieldName})[0].value=f.value;a.parent.isDuplicate&&!c?a.layerValue=
f.value:a.fileValue=f.value;if(f.textbox)f.textbox.title=f.value;else if(f.domNode){var d=f.attr("displayedValue");f.domNode.title=d?d:f.value}}})},_setAddressValues:function(a){var c=a._getAddress(),b=this.csvStore.matchFieldPrefix;a.isDuplicate&&a._useGeomFromLayer||l.forEach(a.addressFields,function(e){var d=b+e.keyField;a.feature.fieldInfo.filter(function(a){return a.name===d})[0].value=c[d];for(var f,k=0;k<a.locationControlTable.rows.length&&(f=a.locationControlTable.rows[k],!f.isAddressRow||
f.keyField!==e.keyField);k++);f.addressValueTextBox.textbox?f.addressValueTextBox.textbox.title=c[d]:f.addressValueTextBox.domNode&&(e=f.addressValueTextBox.attr("displayedValue"),f.addressValueTextBox.domNode.title=e?e:f.addressValueTextBox.value);f.addressValue=c[d]})},_updateFeature:function(a,c,b){var e=this.featureView;e.feature.geometry=a;e._feature.geometry=a;a=[e._feature];e.isDuplicate?(e.isDuplicateLocated||(e.isDuplicateLocated=!0),this._hasGeometryEdit=e._editFeature.geometry.x!==e._feature.geometry.x||
e._editFeature.geometry.y!==e._feature.geometry.y):e.isUnMatched&&!e.isUnMatchedLocated&&(e.isUnMatchedLocated=!0);c||this._updateLayer(e.layer,null,a,null,!1,b).then(d.hitch(this,function(a){a&&"success"===a.status&&(this._panToAndSelectFeature(e._feature),e.emit("address-located"))}))},_locateFeature:function(a){var c=new n,b=this.featureView._getAddressFieldsValues();if(this._isAddressFeature){var e=this.parent.portal?this.parent.portal:this.appConfig.portalUrl?u.getPortal(this.appConfig.portalUrl):
null;this._addressToLocation({address:b,countryCode:this.locatorSource.countryCode,outFields:["ResultID","Score"],forStorage:this.featureView.isDuplicate&&!this.featureView.isDuplicateLocated||this.featureView.isUnMatched&&!this.featureView.isUnMatchedLocated,token:e&&e.credential&&e.credential.token?e.credential.token:null}).then(d.hitch(this,function(b){this.locator=this._getLocator(0);this._updateFeature(b.location,a,!0);c.resolve({feature:this.featureView.feature,address:b.address})}),function(a){new r({message:a.message})})}else b=
this.csvStore._getGeometry(b[this.xField],b[this.yField]),this._updateFeature(b,a,!0),c.resolve({feature:this.featureView.feature,geometry:b});return c},_addressToLocation:function(a){var c=new n;a.maxLocations=1;this.locator.addressToLocations(a,d.hitch(this,function(b){var e=this.csvStore.minScore,d;b&&0<b.length?(l.forEach(b,function(a){"undefined"===typeof d&&a.score>=e&&(d=a);d&&a.score>d.score&&(d=a)}),d?c.resolve(d):this._getNextLocator()?this._addressToLocation(a).then(function(a){c.resolve(a)}):
c.reject({message:this.nls.warningsAndErrors.cannotLocate})):this._getNextLocator()?this._addressToLocation(a).then(function(a){c.resolve(a)}):c.reject({message:this.nls.warningsAndErrors.cannotLocate})}),function(a){c.reject(a)});return c},_getNextLocator:function(){var a=!1,c=this._locatorIndex+1;c<this.csvStore._geocodeSources.length&&(this.locator=this._getLocator(c),a="undefined"!==typeof this.locator);return a},_flashFeatures:function(a){var c;l.forEach(a,d.hitch(this,function(a){if(a.geometry){var b=
H.fromHex(this.styleColor),h=d.clone(b);h.a=.4;b=new w(w.STYLE_CIRCLE,15,new x(x.STYLE_SOLID,b,1),h);a=new I(a.geometry,b);this.map.graphics.add(a);c=a.getLayer?a.getLayer():c;(a=a.getDojoShape())&&D.animateStroke({shape:a,duration:900,color:{start:a.strokeStyle.color,end:a.strokeStyle.color},width:{start:25,end:0}}).play()}}));setTimeout(d.hitch(this,function(b){b&&b.clear&&(b.clear(),a&&(a[0]._layer&&a[0]._layer.infoTemplate||a[0].infoTemplate)&&(this.map.infoWindow.setFeatures(a),this.map.infoWindow.select(0)))}),
1200,c)},_panToAndSelectFeature:function(a){if(a&&a.geometry){var c=this.map.getMaxZoom(),b=Math.round(.25*c);this.map.centerAndZoom(a.geometry,0<c-b?c-b:c).then(d.hitch(this,function(){this._flashFeatures([a])}))}},setStyleColor:function(a){this.styleColor=a},_updateCancel:function(a){this._cancelDisabled=a;this._updateImageNode("bg-cancel","bg-cancel-white","bg-cancel-disabled",this._cancelDisabled,this.domNode);this.cancelButton&&(a?g.set(this.cancelButton,"tabindex","-1"):g.set(this.cancelButton,
"tabindex","0"))},_updateSaveAndCancel:function(a){this._updateSave(a);this._updateCancel(a)},_updateSave:function(a){this._saveDisabled=a;this._updateImageNode("bg-save","bg-save-white","bg-save-disabled",this._saveDisabled,this.domNode);this.saveButton&&(a?g.set(this.saveButton,"tabindex","-1"):g.set(this.saveButton,"tabindex","0"))},_updateLocate:function(a){this._locateDisabled=a;this._updateImageNode("bg-locate","bg-locate-white","bg-locate-disabled",this._locateDisabled,this.featureView.domNode);
a?g.set(this.featureView.locateButton,"tabindex","-1"):g.set(this.featureView.locateButton,"tabindex","0")},_updateSync:function(a){this._syncDisabled=a;this.featureView.syncFields&&(this._updateImageNode("bg-sync","bg-sync-white","bg-sync-disabled",this._syncDisabled,this.featureView.domNode),a?g.set(this.featureView.syncFields,"tabindex","-1"):g.set(this.featureView.syncFields,"tabindex","0"))},updateImageNodes:function(){this._updateImageNode("bg-cancel","bg-cancel-white","bg-cancel-disabled",
this._cancelDisabled,this.domNode);this._updateImageNode("bg-save","bg-save-white","bg-save-disabled",this._saveDisabled,this.domNode);this._updateImageNode("bg-locate","bg-locate-white","bg-locate-disabled",this._locateDisabled,this.featureView.domNode);this._updateImageNode("bg-sync","bg-sync-white","bg-sync-disabled",this._syncDisabled,this.featureView.domNode)},_updateImageNode:function(a,c,b,d,h){var e=this.pageContainer.isDarkTheme,k=d?b:e?c:a,g=e?c:a;d=!1;e=q("."+a,h);e.hasOwnProperty("length")&&
0===e.length?e=q("."+b,h):(d=!0,g=a);!d&&e.hasOwnProperty("length")&&0===e.length?e=q("."+c,h):d||(d=!0,g=b);l.forEach(e,function(a){t.remove(a,g);t.add(a,k)})}})});