// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define(["jimu/shared/BaseVersionManager"],function(m){function k(){this.versions=[{version:"1.0",upgrader:function(a){return a}},{version:"1.1",upgrader:function(a){return a}},{version:"1.2",upgrader:function(a){return a}},{version:"1.3",upgrader:function(a){return a}},{version:"1.4",upgrader:function(a){return a}},{version:"2.0Beta",upgrader:function(a){return a}},{version:"2.0",upgrader:function(a){return a}},{version:"2.0.1",upgrader:function(a){return a}},{version:"2.1",upgrader:function(a){return a}},
{version:"2.2",upgrader:function(a){return a}},{version:"2.3",upgrader:function(a){return a}},{version:"2.4",upgrader:function(a){return a}},{version:"2.5",upgrader:function(a){return a}},{version:"2.6",upgrader:function(a){if(!a||!a.dijits)return a;for(var c=a.dijits,b,d=0;d<c.length;d++)"chart"===c[d].type&&(b=c[d].config.sortOrder,c[d].config.sortOrder={isLabelAxis:!0,isAsc:b?"asc"===b:!0},"feature"===c[d].config.mode&&(c[d].config.sortOrder.field=c[d].config.labelField),c[d].config.maxLabels=
void 0,c[d].config.nullValue="feature"===c[d].config.mode||"count"===c[d].mode?void 0:!0,c[d].config.dateConfig=void 0,c[d].config.useLayerSymbology=void 0);return a}},{version:"2.7",upgrader:function(a){if(!a||!a.dijits)return a;for(var c=a.dijits,b,d=0;d<c.length;d++)if("chart"===c[d].type){b=c[d].config;break}if(!b||!b.mode)return a;var c=b.mode,d=b.type,f=b.valueFields,l=b.colors;l||(l="#5d9cd3 #eb7b3a #a5a5a5 #febf29 #4673c2 #72ad4c".split(" "));var h={};"undefined"!==typeof b.useLayerSymbology&&
"line"===d&&delete b.useLayerSymbology;"undefined"!==typeof b.useLayerSymbology&&(h.useLayerSymbology=b.useLayerSymbology);var e=[];f&&0<f.length&&(e=f);var g=!1;"column"===d||"bar"===d||"line"===d?"line"===d&&"field"===c?e=["line~field"]:"count"===c&&(e=["count~count"]):"pie"===d&&"field"!==c&&(g=!0,e=["pie~not-field"]);f=e.map(function(a,d){var c=l;a={name:a,style:{color:c[d%c.length]}};g&&(a.style.color=c);return a}.bind(this));h.styles={};f&&(h.styles=f);b.seriesStyle=h;"undefined"!==typeof b.colors&&
delete b.colors;"pie"===d||"count"!==c&&"field"!==c||(b.showLegend=!1);"pie"===d&&b.dateConfig&&(b.dateConfig.isNeedFilled=!1);return a}},{version:"2.8",upgrader:function(a){if(!a||!a.dijits)return a;var c=a.dijits.filter(function(a){return"chart"===a.type})[0];if(!c)return a;var b=c&&c.config;if(!b||!b.mode)return a;var d=b.seriesStyle;if(!d)return a;d.type=d.useLayerSymbology?"layerSymbol":"series";"undefined"!==typeof d.useLayerSymbology&&delete d.useLayerSymbology;c.config=function(a){var c={mode:a.mode,
type:a.type},d=c.type,b=c.mode,f=[];"feature"===b?f=f.concat(["labelField","valueFields","sortOrder","maxLabels"]):"category"===b?f=f.concat("categoryField dateConfig valueFields sortOrder operation maxLabels nullValue".split(" ")):"count"===b?f=f.concat(["categoryField","dateConfig","sortOrder","maxLabels"]):"field"===b&&(f=f.concat(["valueFields","operation","sortOrder","maxLabels","nullValue"]));b="backgroundColor seriesStyle showLegend legendTextColor legendTextSize highLightColor".split(" ");
b="pie"===d?b.concat(["showDataLabel","dataLabelColor","dataLabelSize","innerRadius"]):b.concat("showHorizontalAxis horizontalAxisTextColor horizontalAxisTextSize showVerticalAxis verticalAxisTextColor verticalAxisTextSize stack area".split(" "));f.forEach(function(b){c[b]=a[b]});b.forEach(function(b){c[b]=a[b]});c.hasOwnProperty("showLegend")||(c.showLegend=!1);"pie"===d?c.hasOwnProperty("showDataLabel")||(c.showDataLabel=!0):(c.hasOwnProperty("showHorizontalAxis")||(c.showHorizontalAxis=!0),c.hasOwnProperty("showVerticalAxis")||
(c.showVerticalAxis=!0));return c}(b);return a}},{version:"2.9",upgrader:function(a){if(!a||!a.dijits)return a;var c=a.dijits.filter(function(a){return"chart"===a.type})[0];if(!c)return a;var b=c&&c.config;if(!b||!b.mode)return a;b.legend={show:b.showLegend,textStyle:{color:b.legendTextColor,fontSize:b.legendTextSize}};b.xAxis={show:void 0===b.showHorizontalAxis?!0:b.showHorizontalAxis,textStyle:{color:b.horizontalAxisTextColor,fontSize:b.horizontalAxisTextSize},nameTextStyle:{color:b.horizontalAxisTextColor}};
b.yAxis={show:void 0===b.showVerticalAxis?!0:b.showVerticalAxis,textStyle:{color:b.verticalAxisTextColor,fontSize:b.verticalAxisTextSize},nameTextStyle:{color:b.horizontalAxisTextColor}};b.dataLabel={show:b.showDataLabel,textStyle:{color:b.dataLabelColor,fontSize:b.dataLabelSize}};b.marks||(b.marks={});c.config=function(a){var c={mode:a.mode,type:a.type},b=c.type,d=c.mode,e=[];"feature"===d?e=e.concat(["labelField","valueFields","sortOrder","maxLabels"]):"category"===d?e=e.concat("categoryField dateConfig valueFields sortOrder operation maxLabels nullValue".split(" ")):
"count"===d?e=e.concat(["categoryField","dateConfig","sortOrder","maxLabels"]):"field"===d&&(e=e.concat(["valueFields","operation","sortOrder","maxLabels","nullValue"]));d=["backgroundColor","seriesStyle","legend","highLightColor"];d="pie"===b?d.concat(["dataLabel","innerRadius"]):d.concat(["xAxis","yAxis","stack","area","marks"]);e.forEach(function(b){c[b]=a[b]});d.forEach(function(b){c[b]=a[b]});return c}(b);return a}},{version:"2.10",upgrader:function(a){if(!a||!a.dijits)return a;var c=a.dijits,
b=c.filter(function(a){return"gauge"===a.type})[0],c=c.filter(function(a){return"number"===a.type})[0];(function(a){if(a&&a.config){var c=a.config,b=c.min,d=c.max||1E3,e=c.statistic,g="Features"===e.type?"count":e.statisticsType,e="count"!==g?e.fieldName:"",g={type:g};e&&(g.field=e);b=[{type:"value",config:{type:"stat",value:g}},{type:"range",name:"range1",config:{type:"fixed",value:b}},{type:"range",name:"range2",config:{type:"fixed",value:d}}];delete c.statistic;delete c.min;delete c.max;c.statistics=
b;a.config=c}})(b);(function(a){if(a&&a.config){var c=a.config,b=c.statistic,d="Features"===b.type?"count":b.statisticsType,b="count"!==d?b.fieldName:"",d={type:d};b&&(d.field=b);d=[{type:"value",config:{type:"stat",value:d}}];delete c.statistic;c.statistics=d;a.config=c}})(c);return a}},{version:"2.11",upgrader:function(a){return a}},{version:"2.12",upgrader:function(a){function c(a,c){var b=["mode","type"],d=["backgroundColor","seriesStyle","legend","highLightColor"];"feature"===c?b=b.concat(["clusterField",
"valueFields"]):"category"===c?b=b.concat(["clusterField","dateConfig","valueFields","operation","nullValue"]):"count"===c?b=b.concat(["clusterField","dateConfig"]):"field"===c&&(b=b.concat(["valueFields","operation","nullValue"]));b=b.concat(["sortOrder","maxLabels"]);d="pie"===a?d.concat(["dataLabel","innerRadius"]):d.concat(["xAxis","yAxis","stack","area","marks"]);return{dataProperties:b,displayProperties:d}}if(!a||!a.dijits)return a;var b=a.dijits.filter(function(a){return"chart"===a.type})[0];
if(!b)return a;var d=b&&b.config;if(!d||!d.mode)return a;(function(a){if(!a||a.clusterField)return a;if("feature"===a.mode)a.clusterField=a.labelField;else if("category"===a.mode||"count"===a.mode)a.clusterField=a.categoryField})(d);b.config=function(a){if(a){var b=c(a.type,a.mode),d=b.displayProperties,e={},f={};b.dataProperties.forEach(function(b){e[b]=a[b]});d.forEach(function(b){f[b]=a[b]});return{data:e,display:f}}}(d);return a}},{version:"2.13",upgrader:function(a){if(!a||!a.dijits)return a;
var c=a.dijits.filter(function(a){return"chart"===a.type})[0];if(!c)return a;c=c&&c.config;if(!c)return a;var b=c.data&&c.data.mode,d=c.data&&c.data.type,f=c.display;if(!d||!b||!f||f.tooltip)return a;c.display.tooltip={confine:!0,trigger:"pie"===d?"item":"axis"};return a}},{version:"2.14",upgrader:function(a){return a}},{version:"2.15",upgrader:function(a){return a}},{version:"2.16",upgrader:function(a){if(!a||!a.dijits)return a;var c=a.dijits.filter(function(a){return"chart"===a.type})[0];if(!c)return a;
c=c&&c.config;if(!c)return a;var b=c.data&&c.data.type,d=c.data&&c.data.mode,f=c.display;if(!b||!d||!f||"pie"===b)return a;c.display.displayRange="AUTO";return a}}]}k.prototype=new m;return k.prototype.constructor=k});