// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/BusinessAnalyst/SelectPointPolygonPage.html":'\x3cdiv\x3e\r\n    \x3cbr\x3e\r\n    \x3cdiv\x3e${nls.widgetDescription}\x3c/div\x3e\r\n    \x3cbr\x3e\r\n    \x3cdiv\x3e${nls.selectPointOrPolygon}\x3c/div\x3e\r\n    \x3cbr\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"searchContainer" class\x3d"esriBusinessAnalystSearchContainer"\x3e\x3c/div\x3e\r\n    \x3cdiv tabindex\x3d"0" role\x3d"button" data-dojo-attach-point\x3d"activatePinButton" title\x3d"${nls.addPoint}" class\x3d"esriBusinessAnalystButton esriBusinessAnalystPinButton" data-blur-on-click\x3d"true" \x3e\x3c/div\x3e\r\n    \x3cdiv tabindex\x3d"1" role\x3d"button" data-dojo-attach-point\x3d"activatePolygonButton" title\x3d"${nls.addPolygon}" class\x3d"esriBusinessAnalystButton esriBusinessAnalystPolygonButton" data-blur-on-click\x3d"true" \x3e\x3c/div\x3e\r\n    \x3cdiv tabindex\x3d"2" role\x3d"button" data-dojo-attach-point\x3d"activateFreehandPolygonButton" title\x3d"${nls.addFreehandPolygon}" class\x3d"esriBusinessAnalystButton esriBusinessAnalystFreehandPolygonButton" data-blur-on-click\x3d"true" \x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/_base/lang dojo/dom-class dojo/on dojo/when dijit/_TemplatedMixin dijit/_WidgetBase esri/Color esri/dijit/Search esri/dijit/geoenrichment/_WizardPage esri/geometry/webMercatorUtils esri/graphic esri/InfoTemplate esri/symbols/PictureMarkerSymbol esri/symbols/SimpleFillSymbol esri/symbols/SimpleLineSymbol esri/toolbars/draw dojo/text!./SelectPointPolygonPage.html ./utils/GeocodeUtil".split(" "),function(p,f,b,d,q,r,t,g,u,v,h,k,w,x,l,m,n,y,z){return p([t,r,v],{templateString:y,
polygonActive:!1,freehandPolygonActive:!1,postCreate:function(){this.inherited(arguments);var a=this;this.search=(new u({map:this.map})).placeAt(this.searchContainer);this.search.activeSource.outFields.push("country");this.own(d(this.search,"select-result",function(){a._loadSearchResult()}));this.own(d(this.activatePinButton,"click",function(){a._onActivatePinButtonClick()}));this.own(d(this.activatePolygonButton,"click",function(){a._onActivatePolygonButtonClick()}));this.own(d(this.activateFreehandPolygonButton,
"click",function(){a._onActivateFreehandPolygonButtonClick()}))},startup:function(){this._started||b.add(this.layoutGrid.domNode,"business-analyst-search-suggestions-overflow")},_loadSearchResult:function(){this.wizard.selectedPoint.geometry=this.search.selectedResult.feature.geometry;this.wizard.selectedPoint.locationName=this.search.selectedResult.name;var a=h.xyToLngLat(this.search.selectedResult.feature.geometry.x,this.search.selectedResult.feature.geometry.y);this.wizard.selectedPoint.long=a[0].toFixed(5);
this.wizard.selectedPoint.lat=a[1].toFixed(5);this.wizard.setSelectedCountry(this.search.selectedResult.feature.attributes.country);this.onNext()},_onActivatePinButtonClick:function(){this._executeHandler?(this._deactivate(),this._deactivatePolygon(),this._deactivateFreehandPolygon()):(this._deactivatePolygon(),this._deactivateFreehandPolygon(),this._setActive())},_setActive:function(){this._executeHandler||(b.add(this.activatePinButton,"esriBusinessAnalystPressedButton"),this.map.setInfoWindowOnClick(!1),
this.map.setMapCursor("default"),this.map.disablePan(),this._executeHandler=d(this.map,"click",this._addPoint.bind(this)))},_deactivate:function(){this._executeHandler&&(b.remove(this.activatePinButton,"esriBusinessAnalystPressedButton"),this.map.setInfoWindowOnClick(!0),this.map.enablePan(),this._executeHandler.remove(),this._executeHandler=null)},_addPoint:function(a){if(this._executeHandler){this._deactivate();var e=h.xyToLngLat(a.mapPoint.x,a.mapPoint.y),c=this;q(z.reverseGeocode({x:e[0],y:e[1]}),
function(b){var d=new x("https://js.arcgis.com/3.28/esri/dijit/Search/images/search-pointer.png",36,36);c.wizard.selectedPoint.pointGraphic=new k(a.mapPoint,d);c.map.graphics.add(c.wizard.selectedPoint.pointGraphic);c.map.centerAndZoom(a.mapPoint,12);c.wizard.selectedPoint.geometry=a.mapPoint;c.wizard.selectedPoint.locationName=b&&b.address&&b.address.LongLabel?b.address.LongLabel:"";c.wizard.setSelectedCountry(b.address.CountryCode);c.wizard.selectedPoint.long=e[0].toFixed(5);c.wizard.selectedPoint.lat=
e[1].toFixed(5);c.onNext()})}},_onActivatePolygonButtonClick:function(){this.polygonActive?(this._deactivatePolygon(),this._deactivate(),this._deactivateFreehandPolygon()):(this._deactivate(),this._deactivateFreehandPolygon(),this._setActivePolygon())},_setActivePolygon:function(){this.polygonActive||(b.add(this.activatePolygonButton,"esriBusinessAnalystPressedButton"),this.polygonActive=!0,this.toolbar||(this.toolbar=new n(this.map),this.toolbar.on("draw-end",f.hitch(this,this._addPolygon))),this.map.disablePan(),
this.map.setInfoWindowOnClick(!1),this.toolbar.activate("polygon"))},_deactivatePolygon:function(){this.polygonActive&&(b.remove(this.activatePolygonButton,"esriBusinessAnalystPressedButton"),this.toolbar&&(this.toolbar.deactivate(),this.map.enablePan(),this.map.setInfoWindowOnClick(!0)),this.polygonActive=!1)},_onActivateFreehandPolygonButtonClick:function(){this.freehandPolygonActive?(this._deactivateFreehandPolygon(),this._deactivate(),this._deactivatePolygon()):(this._deactivate(),this._deactivatePolygon(),
this._setActiveFreehandPolygon())},_setActiveFreehandPolygon:function(){this.freehandPolygonActive||(b.add(this.activateFreehandPolygonButton,"esriBusinessAnalystPressedButton"),this.freehandPolygonActive=!0,this.toolbar||(this.toolbar=new n(this.map),this.toolbar.on("draw-end",f.hitch(this,this._addPolygon))),this.map.disablePan(),this.map.setInfoWindowOnClick(!1),this.toolbar.activate("freehandpolygon"))},_deactivateFreehandPolygon:function(){this.freehandPolygonActive&&(b.remove(this.activateFreehandPolygonButton,
"esriBusinessAnalystPressedButton"),this.toolbar&&(this.toolbar.deactivate(),this.map.enablePan(),this.map.setInfoWindowOnClick(!0)),this.freehandPolygonActive=!1)},_addPolygon:function(a){this._deactivate();this._deactivatePolygon();this._deactivateFreehandPolygon();var b=new l(l.STYLE_SOLID,new m(m.STYLE_SOLID,new g([199,55,36,1]),2),new g([199,55,36,.5]));a=new k(a.geometry,b);a.attributes={title:this.nls.customPolygon};b=new w;b.title="${title}";b.content=" ";b.info={};b.info.fieldInfos=[];a.setInfoTemplate(b);
this.map.graphics.add(a);this.map.infoWindow.setFeatures([a]);this.map.infoWindow.show(this.map.toScreen(a.geometry.getExtent().getCenter()));this.map.infoWindow.removeActions("addMarker");this.wizard.drawnPolygonGraphic=a}})});