// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("esri/request dojo/json dojo/topic dojo/json dojo/_base/lang dojo/_base/array esri/arcgis/Portal esri/layers/FeatureLayer jimu/LayerInfos/LayerInfos".split(" "),function(l,n,a,p,b,v,q,t,u){return{saveToPortal:function(c,r,f,g,k,h,l){(new q.Portal(f.portalUrl)).signIn().then(b.hitch(this,function(d){var m=d.credential.token,n=d.orgId,q=d.username;if("org_user"===d.role)k.innerHTML=h.createService.format(h.userRole),a.publish("setLastFocusNode",!1);else{var w=f.portalUrl+"sharing/content/users/"+
q+"/createService";this.isNameAvailable(f.portalUrl+"sharing/rest/portals/"+n+"/isServiceNameAvailable",m,c).then(b.hitch(this,function(e){if(e.available)a.publish("setBusyIndicator",!0),this.createFeatureService(w,m,this.getFeatureServiceParams(c,r)).then(b.hitch(this,function(d){if(d.success){var e=d.serviceurl.replace(/rest/g,"rest/admin")+"/addToDefinition";this.addDefinitionToService(e,m,this.getLayerParams(c,r,g,h)).then(b.hitch(this,function(e){if(e.success){e=new t(d.serviceurl+"/0?token\x3d"+
m,{id:c,outFields:["*"]});e._wabProperties={itemLayerInfo:{portalUrl:f.portalUrl,itemId:d.itemId}};r.addLayer(e);var g;if(e.loaded)g=u.getInstanceSync().getLayerInfoById(c),g.enablePopup();else e.on("load",b.hitch(this,function(){g=u.getInstanceSync().getLayerInfoById(c);g.enablePopup()}));e.applyEdits(l,null,null).then(b.hitch(this,function(){a.publish("clear")})).otherwise(b.hitch(this,function(){a.publish("clear")}));a.publish("setBusyIndicator",!1);k.innerHTML=h.successfullyPublished.format('\x3cbr /\x3e\x3ca role\x3d"link" tabindex\x3d"0" aria-label\x3d"'+
h.successfullyPublished+'" href\x3d"'+f.portalUrl+"home/item.html?id\x3d"+d.itemId+'" target\x3d"_blank"\x3e')+"\x3c/a\x3e";a.publish("setLastFocusNode",!0)}}),b.hitch(this,function(c){a.publish("setBusyIndicator",!1);k.innerHTML=h.addToDefinition.format(c.message);a.publish("setLastFocusNode",!1)}))}else a.publish("setBusyIndicator",!1),k.innerHTML=h.unableToCreate.format(c),a.publish("setLastFocusNode",!1)}),b.hitch(this,function(c){a.publish("setBusyIndicator",!1);k.innerHTML=h.createService.format(c.message);
a.publish("setLastFocusNode",!1)}));else{var d=null;v.forEach(this._layerList,b.hitch(this,function(a){a._json&&p.parse(a._json).name&&p.parse(a._json).name===c&&(d=a)}));d?(e=new t(d.url+"?token\x3d"+m,{id:c,outFields:["*"]}),e._wabProperties={itemLayerInfo:{portalUrl:f.portalUrl,itemId:d.id}},e.applyEdits(l,null,null).then(b.hitch(this,function(){a.publish("clear")})).otherwise(b.hitch(this,function(){a.publish("clear")})),a.publish("setBusyIndicator",!1),e='\x3cbr /\x3e\x3ca role\x3d"link" tabindex\x3d"0" aria-label\x3d"'+
h.successfullyAppended+'" href\x3d"'+f.portalUrl+"home/item.html?id\x3d"+p.parse(d._json).serviceItemId+'" target\x3d"_blank"\x3e',k.innerHTML=h.successfullyAppended.format(e)+"\x3c/a\x3e",a.publish("setLastFocusNode",!0)):(a.publish("setBusyIndicator",!1),k.innerHTML=h.layerNameExists,a.publish("setLastFocusNode",!1))}}),b.hitch(this,function(c){a.publish("setBusyIndicator",!1);k.innerHTML=h.checkService.format(c.message);a.publish("setLastFocusNode",!1)}))}}),b.hitch(this,function(c){k.innerHTML=
c.message;a.publish("setLastFocusNode",!1)}))},getFeatureServiceParams:function(c,a){return{name:c,serviceDescription:"",hasStaticData:!1,maxRecordCount:1E3,supportedQueryFormats:"JSON",capabilities:"Create,Delete,Query,Update,Editing",tags:"ThreatAnalysis",description:"",copyrightText:"",spatialReference:{wkid:102100},initialExtent:{xmin:a.extent.xmin,ymin:a.extent.ymin,xmax:a.extent.xmax,ymax:a.extent.ymax,spatialReference:{wkid:102100}},allowGeometryUpdates:!0,units:"esriMeters",xssPreventionInfo:{xssPreventionEnabled:!0,
xssPreventionRule:"InputOnly",xssInputRule:"rejectInvalid"}}},getLayerParams:function(a,b,f,g){return{layers:[{adminLayerInfo:{geometryField:{name:"Shape"},xssTrustedFields:""},id:0,name:a,type:"Feature Layer",displayField:"",description:"",tags:"ThreatAnalysis",copyrightText:"",defaultVisibility:!0,ownershipBasedAccessControlForFeatures:{allowOthersToQuery:!1,allowOthersToDelete:!1,allowOthersToUpdate:!1},relationships:[],isDataVersioned:!1,supportsCalculate:!0,supportsAttachmentsByUploadId:!0,supportsRollbackOnFailureParameter:!0,
supportsStatistics:!0,supportsAdvancedQueries:!0,supportsValidateSql:!0,supportsCoordinatesQuantization:!0,supportsApplyEditsWithGlobalIds:!0,advancedQueryCapabilities:{supportsPagination:!0,supportsQueryWithDistance:!0,supportsReturningQueryExtent:!0,supportsStatistics:!0,supportsOrderBy:!0,supportsDistinct:!0,supportsQueryWithResultType:!0,supportsSqlExpression:!0,supportsReturningGeometryCentroid:!0},useStandardizedQueries:!1,geometryType:"esriGeometryPolygon",minScale:0,maxScale:0,extent:b.extent,
drawingInfo:{renderer:f.toJson(),transparency:0},allowGeometryUpdates:!0,hasAttachments:!1,htmlPopupType:"esriServerHTMLPopupTypeNone",hasM:!1,hasZ:!1,objectIdField:"OBJECTID",globalIdField:"",typeIdField:"",fields:[{name:"OBJECTID",type:"esriFieldTypeOID",actualType:"int",alias:"OBJECTID",sqlType:"sqlTypeOther",nullable:!1,editable:!1,domain:null,defaultValue:null},{name:"zone_type",type:"esriFieldTypeString",alias:g.zoneTypeLabel,actualType:"nvarchar",nullable:!0,editable:!0,domain:null,defaultValue:null,
sqlType:"sqlTypeNVarchar",length:256},{name:"threat_type",type:"esriFieldTypeString",alias:g.threatType,actualType:"nvarchar",nullable:!0,editable:!0,domain:null,defaultValue:null,sqlType:"sqlTypeNVarchar",length:256},{name:"mandatory_dist",type:"esriFieldTypeDouble",alias:g.mandatoryLabel,actualType:"float",nullable:!0,editable:!0,domain:null,defaultValue:null,sqlType:"sqlTypeFloat"},{name:"safe_dist",type:"esriFieldTypeDouble",alias:g.safeLabel,actualType:"float",nullable:!0,editable:!0,domain:null,
defaultValue:null,sqlType:"sqlTypeFloat"},{name:"units",type:"esriFieldTypeString",alias:g.unitsLabel,actualType:"nvarchar",nullable:!0,editable:!0,domain:null,defaultValue:null,sqlType:"sqlTypeNVarchar",length:256}],indexes:[],types:[],templates:[{name:"New Feature",description:"",drawingTool:"esriFeatureEditToolPolygon",prototype:{attributes:{type:""}}}],supportedQueryFormats:"JSON",hasStaticData:!1,maxRecordCount:1E4,standardMaxRecordCount:4E3,tileMaxRecordCount:4E3,maxRecordCountFactor:1,exceedsLimitFactor:1,
capabilities:"Query,Editing,Create,Update,Delete"}]}},isNameAvailable:function(a,b,f){return l({url:a,content:{name:f,type:"Feature Service",token:b,f:"json"},handleAs:"json",callbackParamName:"callback"},{usePost:!0})},createFeatureService:function(a,b,f){return l({url:a,content:{f:"json",token:b,typeKeywords:"ArcGIS Server,Data,Feature Access,Feature Service,Service,Hosted Service",createParameters:n.stringify(f),outputType:"featureService"},handleAs:"json",callbackParamName:"callback"},{usePost:!0})},
addDefinitionToService:function(a,b,f){return l({url:a,content:{token:b,addToDefinition:n.stringify(f),f:"json"},handleAs:"json",callbackParamName:"callback"},{usePost:!0})}}});