// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/array dojo/_base/lang dojo/_base/html dojo/on dojo/aspect dojo/keys dijit/focus dojo/topic jimu/utils jimu/LayoutManager".split(" "),function(q,n,c,h,f,r,d,k,p,e,t){return q(null,{_layoutManager:null,_focusedTab:null,focusToDisplay:!1,hasBeenActivated:!1,postCreate:function(){this.inherited(arguments);this._layoutManager=t.getInstance();this.focusToDisplay=!0;this.hasBeenActivated=this.config.initiallyExpand;this.own(f(this.domNode,"keydown",c.hitch(this,function(a){h.hasClass(a.target,
this.baseClass)&&a.keyCode===d.ENTER&&(this.focusToDisplay=!1,this.hasBeenActivated=!0,this.showing||(this.widgetManager.activateWidget(this),this._switchTable()))})));this.own(f(this.domNode,"focus",c.hitch(this,function(){e.isInNavMode()&&this.focusToDisplay&&!this.showing&&(this.widgetManager.activateWidget(this),this._switchTable())})));this.own(f(this.domNode,"blur",c.hitch(this,function(){e.isInNavMode()&&this.focusToDisplay&&this.showing&&(this.hasBeenActivated||this._switchTable());this.focusToDisplay=
!0;this.showing||(this.hasBeenActivated=!1)})));this.own(p.subscribe(this.id+"_table_created",c.hitch(this,function(a){this._applyA11y2Grid(a&&a.grid,a&&a.context)})),p.subscribe(this.id+"_toolbar_created",c.hitch(this,function(a){this._applyA11y2Toolbar(a&&a.toolbar,a&&a.context)})))},applyA11y:function(){this._isOnlyTable()&&h.removeAttr(this.domNode,"tabindex");this.switchBtn&&this.own(f(this.switchBtn,"keydown",c.hitch(this,function(a){a.keyCode===d.ENTER&&(this._switchTable(),this.focusToDisplay=
this.showing,this.__focus2WidgetNode())})));this.tabContainer&&this.tabContainer.hasChildren()?this._applyA11y2TabContainer(this.tabContainer):this.NoTableMessageDiv&&(h.setAttr(this.NoTableMessageDiv,{tabindex:"0"}),e.initFirstFocusNode(this.domNode,this.NoTableMessageDiv),e.initLastFocusNode(this.domNode,this.NoTableMessageDiv),this.own(f(this.NoTableMessageDiv,"keydown",c.hitch(this,function(a){a.keyCode===d.ESCAPE&&this.__escape2WidgetSwitch(a)}))),this._isOnlyTable()&&k.focus(this.NoTableMessageDiv))},
_applyA11y2TabContainer:function(a){if(a){var b=this,m=function(g){g&&(n.forEach(a.tablist.getChildren(),function(a){!a.active&&a.closeButton&&a.id!==g.id&&h.setAttr(a.closeNode,"tabindex",-1)}),h.setAttr(g.closeNode,"tabindex",0))},u=a.tablist.onkeydown;a.tablist.onkeydown=function(a,m){var c=null,l=!1;switch(a.keyCode){case d.LEFT_ARROW:case d.UP_ARROW:a._djpage||(c=!1);break;case d.PAGE_UP:a.ctrlKey&&(c=!1);break;case d.RIGHT_ARROW:case d.DOWN_ARROW:a._djpage||(c=!0);break;case d.PAGE_DOWN:a.ctrlKey&&
(c=!0);break;case d.HOME:for(var g=this.getChildren(),e=0;e<g.length;e++){var f=g[e];if(!f.disabled){k.focus(f.focusNode);b._focusedTab=f;break}}a.stopPropagation();a.preventDefault();break;case d.END:g=this.getChildren();for(e=g.length-1;0<=e;e--)if(f=g[e],!f.disabled){k.focus(f.focusNode);b._focusedTab=f;break}a.stopPropagation();a.preventDefault();break;case d.DELETE:case 87:this._currentChild.closable&&(a.keyCode==d.DELETE||a.ctrlKey)&&(a.stopPropagation(),a.preventDefault());break;case d.ENTER:case d.SPACE:b.tabForwardStep=
0;break;case d.ESCAPE:"Close"===a.target.title?b._focusedTab&&k.focus(b._focusedTab.focusNode):b.__escape2WidgetSwitch(a);a.stopPropagation();a.preventDefault();break;case d.TAB:if(b.isLoading()){a.stopPropagation();a.preventDefault();return}break;default:l=!0}if(null!==c){this.isLeftToRight()||this.tabPosition&&!/top|bottom/.test(this.tabPosition)||(c=!c);var g=this.getChildren(),e=n.indexOf(g,this.pane2button(b._focusedTab?b._focusedTab.page&&b._focusedTab.page.id:this._currentChild.id)),f=g[e],
h;do e=(e+(c?1:g.length-1))%g.length,h=g[e];while(h.disabled&&h!==f);b._focusedTab=h;k.focus(b._focusedTab.focusNode);a.stopPropagation();a.preventDefault()}l&&u.apply(this,arguments)};if(a.hasChildren()){n.forEach(a.getChildren(),c.hitch(this,function(a){a.controlButton.checked||h.setAttr(a.controlButton.focusNode,"aria-selected","false");a.closable&&h.setAttr(a.controlButton.closeNode,"role","button")}));var l=a.tablist.getChildren()[0];this._focusedTab=l;e.initFirstFocusNode(this.domNode,l.focusNode);
l.closeNode&&m(l);!this._isOnlyTable()||"LaunchpadTheme"!==this.appConfig.theme.name&&"BillboardTheme"!==this.appConfig.theme.name||k.focus(l)}this.own(r.after(a,"selectChild",function(){var a=c.getObject("controlButton",!1,this.selectedChildWidget);a&&(e.initFirstFocusNode(b.domNode,a.focusNode),a.closeNode&&m(a));b._focusedTab=a}),f(a.tablist,"blur",c.hitch(this,function(){this._focusedTab=null})))}},_applyA11y2Toolbar:function(a,b){a&&(c.mixin(a,{_onLeftArrow:function(){},_onRightArrow:function(){}}),
this.own(f(a,"keydown",c.hitch(this,function(b){if(b.keyCode===d.TAB){if(b.shiftKey){if(b.target.id===a._getFirstFocusableChild().id)return}else if(b.target.id===a._getLastFocusableChild().id)return;b.shiftKey?a.focusPrev():a.focusNext();b.stopPropagation();b.preventDefault()}else b.keyCode===d.ESCAPE&&this.__escape2ActiveTab(b)}))),b&&b.toggleColumnsMenuItem&&this.own(f(b.toggleColumnsMenuItem,"click",c.hitch(this,function(a){e.isInNavMode()&&this.__applyA11y2GridHiderMenu(this._activeTable&&this._activeTable.grid)}))))},
_applyA11y2Grid:function(a,b){if(a&&a.hiderToggleNode&&a.hiderMenuNode){var m=a.hiderToggleNode,k=a.hiderMenuNode;e.initLastFocusNode(this.domNode,m);a._customEvtHandlersInitialized||(this.own(f(a,"keydown",c.hitch(this,function(a){a.keyCode===d.ESCAPE&&this.__escape2ActiveTab(a)})),f(m,"keydown",c.hitch(this,function(b){if(b.keyCode===d.SPACE||b.keyCode===d.ENTER)a._toggleColumnHiderMenu(),this.__applyA11y2GridHiderMenu(a),b.stopPropagation(),b.preventDefault()})),f(k,"keydown",c.hitch(this,function(b){b.keyCode===
d.ESCAPE&&(m.focus(),a._hiderMenuOpened&&a._toggleColumnHiderMenu(b),b.stopPropagation(),b.preventDefault())}))),a._customEvtHandlersInitialized=!0);this._focusedTab&&this._focusedTab.checked&&b&&h.setAttr(this._focusedTab.focusNode,"aria-labelledby",this._focusedTab.focusNode.id+" "+this.id+"_"+b.id+"_footer")}},__escape2WidgetSwitch:function(a){this.switchBtn?this.switchBtn.focus():e.isDomFocusable(this.domNode)?this.__focus2WidgetNode():this._controllerDiv&&this._controllerDiv.focus();if(this.closeable&&
this._isOnlyTable()&&this.widgetManager){var b;n.some(this._layoutManager&&this._layoutManager.layoutManager&&this._layoutManager.layoutManager.onScreenWidgetIcons,c.hitch(this,function(a){if(a&&a.widgetConfig&&a.widgetConfig.id===this.id)return b=a,!0}));b?b.domNode.focus():this.widgetManager.closeWidget(this)}a&&(a.stopPropagation(),a.preventDefault())},__focus2WidgetNode:function(){this.domNode.focus()},__escape2ActiveTab:function(a){e.focusFirstFocusNode(this.domNode);a&&(a.stopPropagation(),
a.preventDefault())},__applyA11y2GridHiderMenu:function(a){if(a&&a._hiderMenuOpened&&(a=a.hiderMenuNode,a.children&&0<a.children.length)){var b=a.children[0],c=a.children[a.children.length-1],d=b.querySelector("input");e.initFirstFocusNode(a,b.querySelector("input"));e.initLastFocusNode(a,c.querySelector("input"));d&&d.focus()}},__focusOnActiveTab:function(){setTimeout(c.hitch(this,function(){e.focusFirstFocusNode(this.domNode)}),600)}})});