// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/connect dojo/_base/lang dojo/topic esri/graphic esri/toolbars/draw esri/geometry/Point esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Circle esri/geometry/geometryEngine esri/geometry/webMercatorUtils esri/geometry/geodesicUtils esri/SpatialReference esri/units jimu/utils ./Feedback dojo/has dojo/touch dojo/on".split(" "),function(p,m,f,g,d,q,u,l,r,v,h,n,w,x,y,t,k,z,A,B){k=p([k],{orientationAngle:0,majorAxisLength:[],minorAxisLength:[],signal:null,
constructor:function(a){p.safeMixin(this,a);this.initGeometryService();this.syncEvents();this._majGraphic=new d;this._majGraphicB=new d;this._minGraphic=new d;this._minGraphicB=new d},syncEvents:function(){g.subscribe("create-manual-ellipse",f.hitch(this,this.onCreateManualEllipse));g.subscribe("manual-ellipse-center-point-input",f.hitch(this,this.onCenterPointManualInputHandler));g.subscribe("clear-points",f.hitch(this,this.clearPoints))},clearPoints:function(){this._points=[];this.map.graphics.clear()},
onCreateManualEllipse:function(a,b,c,e){this._points=[];this._points.push(e);this.majorAxisLength=a=this.coordTool.convertToMeters(a,this.lengthUnit);a=this.getEndPoint(e,0,a);this._points.push(a);a=new l({paths:[[[e.x,e.y],[a.x,a.y]]],spatialReference:e.spatialReference});this._majGraphic=new d(a,this.lineSymbol);this._majGraphicB=new d(a,this.lineSymbol);this._majGraphicB.geometry=h.rotate(a,180,e);this.minorAxisLength=a=this.coordTool.convertToMeters(b,this.lengthUnit);a=this.getEndPoint(e,90,
a);this._points.push(a);b=new l({paths:[[[e.x,e.y],[a.x,a.y]]],spatialReference:this.map.spatialReference});this._minGraphic=new d(b,this.lineSymbol);this._minGraphicB=new d(b,this.lineSymbol);this._minGraphicB.geometry=h.rotate(b,180,e);this.orientationAngle=Number(c);this._onDoubleClickHandler()},onCenterPointManualInputHandler:function(a){this._points=[];this._points.push(a.offset(0,0));this.set("startPoint",this._points[0]);this.map.centerAt(a)},getEndPoint:function(a,b,c){b=b?b:0;c=new v(a,{radius:c,
geodesic:!0,numberOfPoints:60});return h.rotate(c,b,a).getPoint(0,0)},_onClickHandler:function(a){var b;this.map.snappingManager&&(b=this.map.snappingManager._snappingPoint);var c=b||a.mapPoint;this._points.push(c.offset(0,0));this._processAfterMapClick(c).then(f.hitch(this,function(a){switch(this._geometryType){case q.POINT:this.set("startPoint",c.offset(0,0));this.set("startPointDD",a);this._drawEnd(c.offset(0,0));this._setTooltipMessage(0);break;case q.POLYLINE:switch(this._points.length){case 1:this.set("startPoint",
this._points[0]);this.set("startPointDD",a);a=new l({paths:[[[c.x,c.y],[c.x,c.y]]],spatialReference:this.map.spatialReference});var b=new l({paths:[[[c.x,c.y],[c.x,c.y]]],spatialReference:this.map.spatialReference});this._majGraphic=new d(a,this.lineSymbol);this._majGraphicB=new d(a,this.lineSymbol);this._minGraphic=new d(b,this.lineSymbol);this._minGraphicB=new d(b,this.lineSymbol);this.map.graphics.add(this._majGraphic);this.map.graphics.add(this._majGraphicB);this.map.graphics.add(this._minGraphic);
this.map.graphics.add(this._minGraphicB);z("esri-touch")&&this.parentWidget.own(B(this.map.root,A.move,f.hitch(this,this._onMouseMoveHandler)));this._onMouseMoveHandlerConnect=m.connect(this.map,"onMouseMove",this._onMouseMoveHandler);this._onDoubleClickHandler_connect=m.connect(this.map,"onDblClick",f.hitch(this,this._onDoubleClickHandler));if(a=this._tooltip)a.innerHTML=t.sanitizeHTML(this.nls.majorAxisTooltipMessage);break;case 2:this._setMajorAxisInfo();this._tooltip&&(this._tooltip.innerHTML=
t.sanitizeHTML(this.nls.minorAxisTooltipMessage));break;case 3:this._setMinorAxisInfo(),this._onDoubleClickHandler()}}}),function(a){console.log(a)})},_setMajorAxisInfo:function(){this.getProjectedGeometry(this._majGraphic.geometry,new x(4326)).then(f.hitch(this,f.hitch(this,function(a){this.majorAxisLength=h.geodesicLength(a,9001);a=this.coordTool.convertMetersToUnits(this.majorAxisLength,this.lengthUnit);g.publish("DD_ELLIPSE_MAJOR_LENGTH_CHANGE",a)})));var a=this.getAngle(n.webMercatorToGeographic(this._points[0]),
n.webMercatorToGeographic(this._majGraphic.geometry.getPoint(0,1)));"mils"===this.angleUnit&&(a*=17.777777778);g.publish("DD_ELLIPSE_ANGLE_CHANGE",a)},_setMinorAxisInfo:function(){var a=f.clone(this._minGraphic.geometry),b=n.webMercatorToGeographic(this._minGraphic.geometry);this.minorAxisLength=w.geodesicLengths([b],y.METERS);b=this.coordTool.convertMetersToUnits(this.minorAxisLength[0],this.lengthUnit);this.minorAxisLength[0]>this.majorAxisLength||0===this.minorAxisLength[0]?this._minGraphic.setGeometry(a):
g.publish("DD_ELLIPSE_MINOR_LENGTH_CHANGE",b)},_onMouseMoveHandler:function(a){var b;this.map.snappingManager&&(b=this.map.snappingManager._snappingPoint);a=b||a.mapPoint;1===this._points.length?(this._majGraphic.geometry.setPoint(0,1,a),this._majGraphicB.geometry=h.rotate(this._majGraphic.geometry,180,this._points[0]),this._majGraphic.setGeometry(this._majGraphic.geometry).setSymbol(this.lineSymbol),this._majGraphicB.setGeometry(this._majGraphicB.geometry).setSymbol(this.lineSymbol),this.canProjectLocally&&
this._setMajorAxisInfo()):null!==this._minGraphic&&(a=h.nearestCoordinate(this._majGraphic.geometry,a),a=new u(a.coordinate.x,a.coordinate.y,102100),this._minGraphic.geometry.setPoint(0,1,a),this._minGraphicB.geometry.setPoint(0,1,a),this._minGraphic.geometry=h.rotate(this._minGraphic.geometry,-90,this._points[0]),this._minGraphicB.geometry=h.rotate(this._minGraphicB.geometry,90,this._points[0]),this._minGraphic.setGeometry(this._minGraphic.geometry).setSymbol(this.lineSymbol),this._minGraphicB.setGeometry(this._minGraphicB.geometry).setSymbol(this.lineSymbol),
this.canProjectLocally&&this._setMinorAxisInfo())},getLineLength:function(a,b,c,e){return Math.sqrt((a-=c)*a+(b-=e)*b)},getAngle:function(a,b){return(180*Math.atan2(b.x-a.x,b.y-a.y)/Math.PI+360)%360},convertAngle:function(a){return 0<=a&&90>a||180<=a&&270>a?90-a:90<=a&&180>a||270<=a&&360>a?180-a+270:a},_onDoubleClickHandler:function(){if(3<=this._points.length){var a=new r(this._points[0].spatialReference),b=[];b.push(this._majGraphic.geometry.getPoint(0,0));b.push(this._majGraphic.geometry.getPoint(0,
1));b.push(this._minGraphic.geometry.getPoint(0,1));this.geomService.project(b,this.map.spatialReference,f.hitch(this,function(b){var c=this.map.toScreen(b[0]),d=this.map.toScreen(b[1]),g=this.map.toScreen(b[2]),d=this.getLineLength(c.x,c.y,d.x,d.y),g=this.getLineLength(c.x,c.y,g.x,g.y),c=r.createEllipse({center:c,longAxis:d,shortAxis:g,numberOfPoints:60,map:this.map});this.orientationAngle=this.angle;"mils"===this.angleUnit&&(this.orientationAngle/=17.777777778);a.geometry=h.rotate(c,this.convertAngle(this.orientationAngle),
b[0]);a=f.mixin(a,{majorAxisLength:this.coordTool.convertMetersToUnits(this.majorAxisLength,this.lengthUnit),minorAxisLength:this.coordTool.convertMetersToUnits(this.minorAxisLength,this.lengthUnit),angle:this.angle,drawType:"ellipse",center:this._points[0]});this.disconnectOnMouseMoveHandler();this._setTooltipMessage(0);this._drawEnd(a);this.cleanup();this.orientationAngle=0}))}},cleanup:function(){this.map.graphics.clear();this._minGraphic=this._majGraphic=null;this.majorAxisLength=[];this.minorAxisLength=
[]},disconnectOnMouseMoveHandler:function(){this._onMouseMoveHandlerConnect&&m.disconnect(this._onMouseMoveHandlerConnect)}});k.DD_ELLIPSE_MAJOR_LENGTH_CHANGE="DD_ELLIPSE_MAJOR_LENGTH_CHANGE";k.DD_ELLIPSE_MINOR_LENGTH_CHANGE="DD_ELLIPSE_MINOR_LENGTH_CHANGE";k.DD_ELLIPSE_ANGLE_CHANGE="DD_ELLIPSE_ANGLE_CHANGE";return k});