// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/topic esri/graphic esri/toolbars/draw esri/geometry/Circle esri/geometry/Polyline esri/geometry/geometryEngine jimu/utils ./Feedback dojo/has dojo/touch dojo/on".split(" "),function(h,d,f,k,g,l,e,m,n,p,q,r,t,u){return h([q],{constructor:function(a){h.safeMixin(this,a);this.syncEvents();this.initGeometryService();this.circlePoints=[];this.geoDesicCirclePoints=[]},syncEvents:function(){k.subscribe("manual-rangering-center-point-input",
d.hitch(this,this.onCenterPointManualInputHandler));k.subscribe("clear-points",d.hitch(this,this.clearPoints))},clearPoints:function(a){a&&(this._points=[],this.circlePoints=[],this.geoDesicCirclePoints=[],this.map.graphics.clear())},clearGraphics:function(){this.map.graphics.clear()},onCenterPointManualInputHandler:function(a){this._points=[];this.circlePoints=[];this.geoDesicCirclePoints=[];this._points.push(a.offset(0,0));this.set("startPoint",this._points[0]);this.map.centerAt(a)},_onClickHandler:function(a){var c;
this.map.snappingManager&&(c=this.map.snappingManager._snappingPoint);var b=c||a.mapPoint,e=this.map;this._points.push(b.offset(0,0));this._processAfterMapClick(b).then(d.hitch(this,function(a){1===this._points.length?(this.canProjectLocally||(this.geoDesicCirclePoints=[],this.circlePoints=[]),this.set("startPoint",this._points[0]),this.set("startPointDD",a)):this.set("endPointDD",a);this.circlePoints.push(b.offset(0,0));this.geoDesicCirclePoints.push(a.offset(0,0));switch(this._geometryType){case l.POINT:this._drawEnd(a.offset(0,
0));this._setTooltipMessage(0);break;case l.POLYLINE:a=new m({paths:[[[b.x,b.y],[b.x,b.y]]],spatialReference:e.spatialReference}),this.lgraphic=new g(a,this.lineSymbol),e.snappingManager&&e.snappingManager._setGraphic(this._graphic),1<this._points.length&&this._drawRangeCircle(),0<this._points.length&&(r("esri-touch")&&this.parentWidget.own(u(this.map.root,t.move,d.hitch(this,this._onMouseMoveHandler))),!this._onMouseMoveHandler_connect&&this.canProjectLocally&&(this._onMouseMoveHandler_connect=f.connect(this.map,
"onMouseMove",this._onMouseMoveHandler)),this._onDoubleClickHandler_connect||(this._onDoubleClickHandler_connect=f.connect(this.map,"onDblClick",d.hitch(this,this._onDoubleClickHandler))))}this._setTooltipMessage(this._points.length);1<this._points.length&&(a=this._tooltip)&&(a.innerHTML=p.sanitizeHTML(this.nls.doubleClickEllipseMesage))}))},_drawRangeCircle:function(){if(this.canProjectLocally)this.circleGraphic&&(a=new g(this.circleGraphic.geometry,this.fillSymbol),this.map.graphics.add(a));else{var a=
new m({paths:[[[this.startPointDD.x,this.startPointDD.y],[this.endPointDD.x,this.endPointDD.y]]],spatialReference:this.startPointDD.spatialReference}),a=n.geodesicLength(a,9001),c=new e(this.startPointDD,{radius:a,geodesic:!0,numberOfPoints:360});this.geodsicCircleGeometry=new e(this.startPointDD,{radius:a,geodesic:!0,numberOfPoints:360});this.getProjectedGeometry(c,this.map.spatialReference).then(d.hitch(this,d.hitch(this,function(a){c=d.mixin(a,{distanceDirectionType:"military-tools-range-rings"});
this.circleGraphic=new g(c,this.fillSymbol);this.map.graphics.add(this.circleGraphic)})))}},_onMouseMoveHandler:function(a){var c;this.map.snappingManager&&(c=this.map.snappingManager._snappingPoint);var b=this._points[0];a=c||a.mapPoint;c=this.lgraphic.geometry;c.setPoint(0,0,{x:b.x,y:b.y});c.setPoint(0,1,{x:a.x,y:a.y});a=n.geodesicLength(c,9001);b=new e(b,{radius:a,geodesic:!0,numberOfPoints:360});this.geodsicCircleGeometry=new e(this.startPointDD,{radius:a,geodesic:!0,numberOfPoints:360});this.circleGraphic&&
this.map.graphics.remove(this.circleGraphic);b=d.mixin(b,{distanceDirectionType:"military-tools-range-rings"});this.circleGraphic=new g(b,this.fillSymbol);this.map.graphics.add(this.circleGraphic)},_onDoubleClickHandler:function(){if(this.geoDesicCirclePoints&&!(2>this.geoDesicCirclePoints.length)){this.disconnectOnMouseMoveHandlers();var a=d.clone(this.geoDesicCirclePoints);this.cleanup();this._clear();this._setTooltipMessage(0);a=d.mixin(this.geodsicCircleGeometry,{circlePoints:a});this._drawEnd(a)}},
disconnectOnMouseMoveHandlers:function(){f.disconnect(this._onMouseMoveHandler_connect);f.disconnect(this._onDoubleClickHandler_connect);this._onDoubleClickHandler_connect=null},cleanup:function(){for(var a=this.map.graphics.graphics.length-1;0<=a;a--)this.map.graphics.graphics[a].geometry.hasOwnProperty("distanceDirectionType")&&this.map.graphics.remove(this.map.graphics.graphics[a]);this.circlePoints=[];this.geoDesicCirclePoints=[]}})});