// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/array dojo/when esri/request ./GeocodeUtil esri/geometry/webMercatorUtils esri/dijit/geoenrichment/utils/FileUtil jimu/portalUtils".split(" "),function(h,l,k,m,n,p,f){return{getAvailableCountries:function(){return f.getPortal(portalUrl).loadSelfInfo().then(function(a){return k({url:(a&&a.helperServices&&a.helperServices.geoenrichment&&a.helperServices.geoenrichment.url?a.helperServices.geoenrichment.url:"https://geoenrich.arcgis.com/arcgis/rest/services/World/geoenrichmentserver")+
"/Geoenrichment/Countries",content:{appID:"webappbuilder",f:"json",langCode:"en-us"},handleAs:"json"})})},createRingOrDriveTimes:function(a){return f.getPortal(portalUrl).loadSelfInfo().then(function(b){return k({url:(b&&b.helperServices&&b.helperServices.geoenrichment&&b.helperServices.geoenrichment.url?b.helperServices.geoenrichment.url:"https://geoenrich.arcgis.com/arcgis/rest/services/World/geoenrichmentserver")+"/Geoenrichment/Enrich",content:{appID:"webappbuilder",f:"json",langCode:"en-us",
useData:JSON.stringify({sourceCountry:a.sourceCountry}),studyAreasOptions:JSON.stringify(a.studyAreasOptions),dataCollections:JSON.stringify(["GlobalIntersect"]),returnGeometry:!0,outSR:JSON.stringify({wkid:102100}),studyAreas:JSON.stringify([{geometry:a.geometry}]),token:esri.id.credentials[0].token},handleAs:"json"})})},createReport:function(a){var b={appID:"webappbuilder",langCode:"en-us",report:"string"===typeof a.report?a.report:JSON.stringify(a.report),format:"pdf",f:"bin",token:esri.id.credentials[0].token,
useData:JSON.stringify({sourceCountry:a.sourceCountry}),studyAreas:JSON.stringify(a.studyAreas),reportFields:JSON.stringify({locationname:a.locationName,latitude:a.lat,longitude:a.long,subtitle:"Prepared by Esri",areadesc2:a.areadesc2})};return f.getPortal(portalUrl).loadSelfInfo().then(function(d){return k({url:(d&&d.helperServices&&d.helperServices.geoenrichment&&d.helperServices.geoenrichment.url?d.helperServices.geoenrichment.url:"https://geoenrich.arcgis.com/arcgis/rest/services/World/geoenrichmentserver")+
"/Geoenrichment/createReport",content:b,handleAs:"blob"}).then(function(b){return p.saveAs(b,a.reportDownloadName+".pdf")}).otherwise(function(a){alert("Error: "+a)})})},checkCapabilities:function(a){return f.getPortal(portalUrl).loadSelfInfo().then(function(b){var d=!1,c=!1,e=b&&b.user&&b.user.privileges,g=b&&b.helperServices;b=g.geoenrichment&&g.geoenrichment.url;var g=g.routingUtilities&&g.routingUtilities.url,f=b?b:"https://geoenrich.arcgis.com/arcgis/rest/services/World/geoenrichmentserver";
!window.isBuilder&&!a.mode&&a.appProxies&&0<a.appProxies.length&&h.some(a.appProxies,function(a){return f.toLowerCase()===a.sourceUrl.toLowerCase()})?c=d=!0:h.forEach(e,function(a){"premium:user:geoenrichment"===a?d=!0:"premium:user:networkanalysis"===a&&(c=!0)});return{hasPrivilege:d&&c,geServiceConfigured:!!b,dirRoutingServiceConfigured:!!g}})},getCountryForPolygon:function(a,b,d){return f.getPortal(portalUrl).loadSelfInfo().then(function(c){return k({url:(c&&c.helperServices&&c.helperServices.geoenrichment&&
c.helperServices.geoenrichment.url?c.helperServices.geoenrichment.url:"https://geoenrich.arcgis.com/arcgis/rest/services/World/geoenrichmentserver")+"/Geoenrichment/Enrich",content:{appID:"webappbuilder",f:"json",langCode:"en-us",dataCollections:JSON.stringify(["GlobalIntersect"]),outSR:JSON.stringify({wkid:102100}),studyAreas:JSON.stringify([{geometry:a.toJson()}]),token:esri.id.credentials[0].token},handleAs:"json"}).then(function(e){if(e&&e.results&&1===e.results.length&&1===e.results[0].value.FeatureSet[0].features.length)return e.results[0].value.FeatureSet[0].features[0].attributes.sourceCountry;
if(e&&e.results&&1===e.results.length&&1<e.results[0].value.FeatureSet[0].features.length){var c=a.getCentroid(),c=n.xyToLngLat(c.x,c.y),f=function(a){var c="";h.forEach(a,function(a){a.attributes.sourceCountry==d&&(c=d)});if(c)return c;h.forEach(a,function(a){a.attributes.sourceCountry==b.defaultCountryID&&(c=defaultCountryID)});return c?c:a[0].attributes.sourceCountry};return l(m.reverseGeocode({x:c[0],y:c[1]})).then(function(a){return a&&a.address&&a.address.CountryCode?a.address.CountryCode:f(e.results[0].value.FeatureSet[0].features)}).otherwise(function(){return f(e.results[0].value.FeatureSet[0].features)})}return b.defaultCountryID})})},
getGEProxyUrl:function(a){var b=!1;return f.getPortal(portalUrl).loadSelfInfo().then(function(d){geUrl=d&&d.helperServices&&d.helperServices.geoenrichment&&d.helperServices.geoenrichment.url?d.helperServices.geoenrichment.url:"https://geoenrich.arcgis.com/arcgis/rest/services/World/geoenrichmentserver";!window.isBuilder&&!a.mode&&a.appProxies&&0<a.appProxies.length&&h.forEach(a.appProxies,function(a){geUrl.toLowerCase()===a.sourceUrl.toLowerCase()&&(b=a.proxyUrl)});return b})}}});