// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/Deferred dojo/promise/all dojo/when dojo/_base/array esri/request jimu/portalUtils dojo/i18n!../nls/strings".split(" "),function(n,u,q,f,g,v,h){STANDARD_INFOGRAPHIC_TYPEKEYWORD="esriReportPlayerStandardInfographic";return{_ownedCachedCustomReports:null,_sharedCachedCustomReports:null,_cachedCountryClassicReports:[],_cachedInfographicReports:null,_countryInitDfds:[],getAvailableClassicReports:function(b,c){var a=this,e=[],r=new n,d;c&&f.forEach(c.countryConfig,function(a){b==a.countryID&&
(d=a)});d||(d={countryID:b,allowEsriReports:!0,allowAllEsriReports:!0,allowEsriInfographics:!0,allowAllEsriInfographics:!0,allowMyReports:!0,allowMyInfographics:!0,allowSharedReports:!0,allowSharedInfographics:!0,allowAllOrgReports:!0,allowAllOrgInfographics:!0,enabledEsriReports:[],enabledOrgReports:[],enabledEsriInfographics:[],enabledOrgInfographics:[]});var l=null,g=null,m=null;q(this._initReports(b),function(){if(!c||d.allowAllEsriReports||a._hasEnabledReports(a._cachedCountryClassicReports[b],
d.enabledEsriReports))l=e.length,e.push({value:"esriReports",label:h.esriReports,children:[]});if(!c||d.allowAllOrgReports&&a._hasReportsForCountry(a._ownedCachedCustomReports,b)||a._hasEnabledReportsForCountry(a._ownedCachedCustomReports,b,d.enabledOrgReports))g=e.length,e.push({value:"myReports",label:h.myReports,children:[]});if(!c||d.allowAllOrgReports&&a._hasReportsForCountry(a._sharedCachedCustomReports,b)||a._hasEnabledReportsForCountry(a._sharedCachedCustomReports,b,d.enabledOrgReports))m=
e.length,e.push({value:"sharedReports",label:h.sharedReports,children:[]});(d.allowAllEsriReports||a._hasEnabledReports(a._cachedCountryClassicReports[b],d.enabledEsriReports))&&a._cachedCountryClassicReports[b]&&0<a._cachedCountryClassicReports[b].length&&f.forEach(a._cachedCountryClassicReports[b],function(b){(d.allowAllEsriReports||d.enabledEsriReports.includes(b.reportID))&&e[l].children.push(a._formatClassicReportsForDropDown(b))});var k=["esriWebInfographicReport","esriWebSingleInfographic",
"esriWebBlankInfographic","esriWebHiddenInfographic","esriWebComparisonReport"];(d.allowAllOrgReports&&a._hasReportsForCountry(a._ownedCachedCustomReports,b)||a._hasEnabledReportsForCountry(a._ownedCachedCustomReports,b,d.enabledOrgReports))&&f.forEach(a._ownedCachedCustomReports,function(c){c.properties.countries.includes(b)&&(d.allowAllOrgReports||d.enabledOrgReports.includes(c.id))&&(c.typeKeywords.some(function(a){return 0<=k.indexOf(a)})||e[g].children.push(a._formatClassicReportsForDropDown(c)))});
(d.allowAllOrgReports&&a._hasReportsForCountry(a._sharedCachedCustomReports,b)||a._hasEnabledReportsForCountry(a._sharedCachedCustomReports,b,d.enabledOrgReports))&&f.forEach(a._sharedCachedCustomReports,function(c){c.properties.countries.includes(b)&&(d.allowAllOrgReports||d.enabledOrgReports.includes(c.id))&&(c.typeKeywords.some(function(a){return 0<=k.indexOf(a)})||e[m].children.push(a._formatClassicReportsForDropDown(c)))});var p=function(a,b){a=a.label.toUpperCase();b=b.label.toUpperCase();var d=
0;a>b?d=1:a<b&&(d=-1);return d};0<e.length&&e[0].children.sort(p);1<e.length&&e[1].children.sort(p);2<e.length&&e[2].children.sort(p);r.resolve(e)});return r},_hasEnabledReports:function(b,c){return b&&c?f.some(b,function(a){return c.includes(a.reportID)}):!1},_hasReportsForCountry:function(b,c){return b&&c?f.some(b,function(a){return a.properties.countries.includes(c)}):!1},_hasEnabledReportsForCountry:function(b,c,a){return b&&c&&a?f.some(b,function(b){return b.properties.countries.includes(c)?
a.includes(b.id):!1}):!1},_formatClassicReportsForDropDown:function(b){return b.metadata?{label:b.metadata.title,value:b.reportID,reportType:b.metadata.type}:{label:b.title,value:b.id,reportType:b.properties.type,item:{itemid:b.id,url:portalUrl,token:esri.id.credentials[0].token}}},getAvailableInfographicReports:function(b,c){var a=this,e=[],g=new n,d;c&&f.forEach(c.countryConfig,function(a){b==a.countryID&&(d=a)});d||(d={countryID:b,allowEsriReports:!0,allowAllEsriReports:!0,allowEsriInfographics:!0,
allowAllEsriInfographics:!0,allowMyReports:!0,allowMyInfographics:!0,allowSharedReports:!0,allowSharedInfographics:!0,allowAllOrgReports:!0,allowAllOrgInfographics:!0,enabledEsriReports:[],enabledOrgReports:[],enabledEsriInfographics:[],enabledOrgInfographics:[]});var l=null,t=null,m=null;q(this._initReports(b),function(){if(!c||d.allowAllEsriInfographics||a._hasEnabledInfographics(a._cachedInfographicReports,d.enabledEsriInfographics))l=e.length,e.push({value:"esriReports",label:h.esriInfographics,
children:[]});if(!c||d.allowAllOrgInfographics&&0<a._ownedCachedCustomReports.length||a._hasEnabledInfographics(a._ownedCachedCustomReports,d.enabledOrgInfographics))t=e.length,e.push({value:"myReports",label:h.myInfographics,children:[]});if(!c||d.allowAllOrgInfographics&&0<a._sharedCachedCustomReports.length||a._hasEnabledInfographics(a._sharedCachedCustomReports,d.enabledOrgInfographics))m=e.length,e.push({value:"sharedReports",label:h.sharedInfographics,children:[]});(d.allowAllEsriInfographics||
a._hasEnabledInfographics(a._cachedInfographicReports,d.enabledEsriInfographics))&&f.forEach(a._cachedInfographicReports,function(c){c.properties.countries.includes(b)&&(d.allowAllEsriInfographics||d.enabledEsriInfographics.includes(c.id))&&e[l].children.push(a._formatInfographicReportsForDropDown(c))});(d.allowAllOrgInfographics&&0<a._ownedCachedCustomReports.length||a._hasEnabledInfographics(a._ownedCachedCustomReports,d.enabledOrgInfographics))&&f.forEach(a._ownedCachedCustomReports,function(c){c.properties.countries.includes(b)&&
(d.allowAllOrgInfographics||d.enabledOrgInfographics.includes(c.id))&&(c.typeKeywords.includes("esriWebInfographicReport")||a._isOldPortalInfographic(c))&&e[t].children.push(a._formatInfographicReportsForDropDown(c))});(d.allowAllOrgInfographics&&0<a._sharedCachedCustomReports.length||a._hasEnabledInfographics(a._sharedCachedCustomReports,d.enabledOrgInfographics))&&f.forEach(a._sharedCachedCustomReports,function(c){c.properties.countries.includes(b)&&(d.allowAllOrgInfographics||d.enabledOrgInfographics.includes(c.id))&&
(c.typeKeywords.includes("esriWebInfographicReport")||a._isOldPortalInfographic(c))&&e[m].children.push(a._formatInfographicReportsForDropDown(c))});var k=function(a,b){a=a.label.toUpperCase();b=b.label.toUpperCase();var d=0;a>b?d=1:a<b&&(d=-1);return d};0<e.length&&e[0].children.sort(k);1<e.length&&e[1].children.sort(k);2<e.length&&e[2].children.sort(k);g.resolve(e)});return g},_hasEnabledInfographics:function(b,c){return f.some(b,function(a){return c.includes(a.id)})},_isOldPortalInfographic:function(b){return b.properties&&
b.properties.isHidden&&"true"===b.properties.isHidden?!1:b.properties&&b.properties.isGraphicReport&&"true"===b.properties.isGraphicReport?!0:!1},_formatInfographicReportsForDropDown:function(b){return{label:b.title,value:b.id}},_initReports:function(b){var c=[],a=this;if(this._countryInitDfds[b])return this._countryInitDfds[b];this._countryInitDfds[b]=new n;v.getPortal(portalUrl).loadSelfInfo().then(function(e){var h=e&&e.helperServices&&e.helperServices.geoenrichment&&e.helperServices.geoenrichment.url?
e.helperServices.geoenrichment.url:"https://geoenrich.arcgis.com/arcgis/rest/services/World/geoenrichmentserver";a._cachedCountryClassicReports[b]||c.push(g({url:h+"/Geoenrichment/reports/"+b,content:{appID:"webappbuilder",f:"json",langCode:"en-us"}}).then(function(d){a._cachedCountryClassicReports[b]=d.reports},function(a){alert(a)}));a._cachedInfographicReports||(a._cachedInfographicReports=[],c.push(g({url:portalUrl+"/sharing/rest/search",content:{appID:"webappbuilder",f:"json",start:1,num:100,
sortField:"modified",sortOrder:"desc",q:"typekeywords:(esriReportPlayerStandardInfographic jsapiVersion3.32)"}}).then(function(b){f.forEach(b.results,function(b){a._cachedInfographicReports.push(b)})},function(a){alert(a)})));a._ownedCachedCustomReports||(a._ownedCachedCustomReports=[],c.push(g({url:portalUrl+"/sharing/rest/search",content:{appID:"webappbuilder",f:"json",start:1,num:100,sortField:"modified",sortOrder:"desc",q:'type:"Report Template" typekeywords:(esriWebReport NOT esriWebSingleInfographic) owner:'+
esri.id.credentials[0].userId}}).then(function(b){f.forEach(b.results,function(b){a._ownedCachedCustomReports.push(b)})},function(a){alert(a)})));a._sharedCachedCustomReports||(a._sharedCachedCustomReports=[],c.push(g({url:portalUrl+"/sharing/rest/search",content:{appID:"webappbuilder",f:"json",start:1,num:100,sortField:"modified",sortOrder:"desc",q:'access:shared type:"Report Template" typekeywords:(esriWebReport NOT esriWebSingleInfographic) NOT owner:'+esri.id.credentials[0].userId}}).then(function(b){f.forEach(b.results,
function(b){a._sharedCachedCustomReports.push(b)})},function(a){alert(a)})),c.push(g({url:portalUrl+"/sharing/rest/search",content:{appID:"webappbuilder",f:"json",start:1,num:100,sortField:"modified",sortOrder:"desc",q:'access:org type:"Report Template" typekeywords:(esriWebReport NOT esriWebSingleInfographic) NOT owner:'+esri.id.credentials[0].userId}}).then(function(b){f.forEach(b.results,function(b){a._sharedCachedCustomReports.push(b)})},function(a){alert(a)})),e&&e.appInfo&&e.appInfo.orgId&&
c.push(g({url:portalUrl+"/sharing/rest/search",content:{appID:"webappbuilder",f:"json",start:1,num:100,sortField:"modified",sortOrder:"desc",q:'access:public type:"Report Template" typekeywords:(esriWebReport NOT esriWebSingleInfographic) NOT owner:'+esri.id.credentials[0].userId+" orgid: "+e.id}}).then(function(b){f.forEach(b.results,function(b){a._sharedCachedCustomReports.push(b)})},function(a){alert(a)})));0===c.length?a._countryInitDfds[b].resolve():u(c).then(function(){a._countryInitDfds[b].resolve()})});
return this._countryInitDfds[b]}}});