// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/Deferred dojo/on dojo/when dojo/promise/all jimu/BaseWidget jimu/portalUtils jimu/utils esri/lang esri/request esri/dijit/Search esri/tasks/locator esri/layers/FeatureLayer esri/InfoTemplate".split(" "),function(t,f,g,l,n,p,m,u,v,h,q,w,x,y,z,A){return t([u],{baseClass:"jimu-search-layers",declaredClass:"jimu.dijit.SearchLayers",_searchDijitReady:null,_searchDijit:null,_layerInfosObj:null,_esriLocatorRegExp:/geocode(.){0,3}\.arcgis.com\/arcgis\/rest\/services\/World\/GeocodeServer/g,
_mainWidgetNode:null,constructor:function(b,a,c,d,e){this._mainWidgetNode=e;this._searchDijitReady=new l;this._layerInfosObj=c;this.own(c.on("layerInfosFilterChanged",f.hitch(this,this._onLayerInfosFilterChanged)));p(this._getConfigInfo(b,a)).then(f.hitch(this,function(a){return m(this._convertConfig(a)).then(function(a){return g.filter(a,function(a){return a})})})).then(f.hitch(this,function(a){b.sources=a;this._searchDijit=new x(b,d);this._searchDijit.startup();this.setFocus();this._searchDijitReady.resolve(this._searchDijit)}))},
searchDijit:function(){return this._searchDijitReady},setFocus:function(){this._searchDijit&&(this._mainWidgetNode.openAtStartAysn=!0,h.isAutoFocusFirstNodeWidget(this._mainWidgetNode)&&this._searchDijit.inputNode.focus())},destroy:function(){this._searchDijit&&(this._searchDijit.destroy(),this._searchDijit=null);this.inherited(arguments)},_onLayerInfosFilterChanged:function(b){g.some(b,f.hitch(this,function(a){this._searchDijit&&this._searchDijit.sources&&0<this._searchDijit.sources.length&&g.forEach(this._searchDijit.sources,
function(b){b._featureLayerId===a.id&&b.featureLayer.setDefinitionExpression(a.getFilter())})}))},_getConfigInfo:function(b,a){return b&&b.sources&&0<b.sources.length?(a=null,this._searchLayer(b.map)&&b.upgradeFromGeocoder?(a=b.map.itemInfo.itemData.applicationProperties.viewing.search,a=g.map(a.layers,f.hitch(this,function(a,d){d.hintText=a;return this._getQueryTypeGeocoder(b.map,d)},a.hintText)),m(a).then(f.hitch(this,function(a){b.sources=[].concat(a).concat(b.sources);return b}))):b):p(this._getSourcesFromPortalAndWebmap(b.map,
a)).then(f.hitch(this,function(a){return{allPlaceholder:"",showInfoWindowOnSelect:!1,sources:a}}))},_convertConfig:function(b){return g.map(b.sources,f.hitch(this,function(a){var c=new l;if(a&&a.url&&"locator"===a.type){var d={locator:new y(a.url||""),outFields:["*"],singleLineFieldName:a.singleLineFieldName||"",name:h.stripHTML(a.name||""),placeholder:h.stripHTML(a.placeholder||""),countryCode:a.countryCode||"",maxSuggestions:a.maxSuggestions,maxResults:a.maxResults||6,zoomScale:a.zoomScale||5E4,
useMapExtent:!!a.searchInCurrentMapExtent};a.enableLocalSearch&&(d.localSearchOptions={minScale:a.localSearchMinScale,distance:a.localSearchDistance});c.resolve(d)}else a&&a.url&&"query"===a.type?(d=new z(a.url||null,{outFields:["*"]}),this.own(n(d,"load",f.hitch(this,function(e){var d=e.layer,f=this._getInfoTemplate(d,a,a.displayField),k=null;a.searchFields&&0<a.searchFields.length?k=a.searchFields:(k=[],g.forEach(d.fields,function(a){"esriFieldTypeOID"!==a.type&&a.name!==d.objectIdField&&"esriFieldTypeGeometry"!==
a.type&&k.push(a.name)}));e={featureLayer:d,outFields:["*"],searchFields:k,displayField:a.displayField||"",exactMatch:!!a.exactMatch,name:h.stripHTML(a.name||""),placeholder:h.stripHTML(a.placeholder||""),maxSuggestions:a.maxSuggestions||6,maxResults:a.maxResults||6,zoomScale:a.zoomScale||5E4,infoTemplate:f,useMapExtent:!!a.searchInCurrentMapExtent,_featureLayerId:a.layerId,enableHighlight:!0,showInfoWindowOnSelect:b.showInfoWindowOnSelect,enableInfoWindow:b.showInfoWindowOnSelect};f||delete e.infoTemplate;
e._featureLayerId&&(f=this._layerInfosObj.getLayerInfoById(e._featureLayerId),d.setDefinitionExpression(f.getFilter()));c.resolve(e)}))),this.own(n(d,"error",function(){c.resolve(null)}))):c.resolve(null);return c}))},_getInfoTemplate:function(b,a,c){var d=this._layerInfosObj.getLayerInfoById(a.layerId),e=d&&d.getInfoTemplate(),r=d&&e;if(d&&!r)return null;r||(e=new A,e.setTitle("\x26nbsp;"),e.setContent(f.hitch(this,"_formatContent",a.name,b,c)));return e},_getSourcesFromPortalAndWebmap:function(b,
a){var c=[],d=null;this._searchLayer(b)&&(d=b.itemInfo.itemData.applicationProperties.viewing.search,g.forEach(d.layers,f.hitch(this,function(a,d){d.hintText=a;c.push(this._getQueryTypeGeocoder(b,d))},d.hintText)));return v.getPortalSelfInfo(a).then(f.hitch(this,function(a){if((a=a.helperServices&&a.helperServices.geocode)&&0<a.length)for(var b=0,d=a.length;b<d;b++){var e=a[b];e&&c.push(this._processSingleLine(e))}return m(c).then(f.hitch(this,function(a){for(var b=[],d=0;d<a.length;d++){var c=a[d];
c&&(c&&"query"===c.type||(c={name:c.name||this._getGeocodeName(c.url),url:c.url,singleLineFieldName:c.singleLineFieldName,placeholder:c.placeholder||c.name||this._getGeocodeName(c.url),maxResults:6,searchInCurrentMapExtent:!1,type:"locator"},c.enableLocalSearch=this._isEsriLocator(c.url),c.localSearchMinScale=3E5,c.localSearchDistance=5E4),b.push(c))}return b}))}))},_getQueryTypeGeocoder:function(b,a){b=b.getLayer(a.id);var c=null,d=null,e=null,e=q.isDefined(a.subLayer)?a.id+"_"+a.subLayer:a.id,c=
this._layerInfosObj.traversal(function(a){return a.id===e?(d=a,!0):!1});return b&&c&&d?(c=q.isDefined(a.subLayer)?d.url||b.url+"/"+a.subLayer:d.url||b.url,{name:d.title,layerId:e,url:c,placeholder:a.hintText,searchFields:[a.field.name],displayField:a.field.name,exactMatch:a.field.exactMatch||!1,maxResults:6,searchInCurrentMapExtent:!1,type:"query"}):null},_isEsriLocator:function(b){this._esriLocatorRegExp.lastIndex=0;return this._esriLocatorRegExp.test(b)},_processSingleLine:function(b){if(b.singleLineFieldName)return b;
if(this._isEsriLocator(b.url))return b.singleLineFieldName="SingleLine",b;var a=new l;w({url:b.url,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}).then(f.hitch(this,function(c){c.singleLineAddressField&&c.singleLineAddressField.name?(b.singleLineFieldName=c.singleLineAddressField.name,a.resolve(b)):(console.warn(b.url+"has no singleLineFieldName"),a.resolve(null))}),f.hitch(this,function(b){console.error(b);a.resolve(null)}));return a.promise},_getGeocodeName:function(b){if("string"!==
typeof b)return"geocoder";b=b.split("/");return b[b.length-2]||"geocoder"},_getGeocoderName:function(b){return this._getGeocodeName(b)},_hasAppSearchInfo:function(b){return b.itemInfo&&b.itemInfo.itemData&&b.itemInfo.itemData.applicationProperties&&b.itemInfo.itemData.applicationProperties.viewing&&b.itemInfo.itemData.applicationProperties.viewing.search},_searchLayer:function(b){if(!this._hasAppSearchInfo(b))return!1;b=b.itemInfo.itemData.applicationProperties.viewing.search;return b.enabled&&0!==
b.layers.length?!0:!1}})});